config/routes.rb
# encoding: utf-8

# NOTES:
# (/u/:user_domain)                -> This allows support of org-urls (support != enforcement)
# defaults: { dont_rewrite: true } -> Use this to force an individual action to not get rewritten to org-url
# Can be also done at controller source files by using -> skip_before_filter :ensure_org_url_if_org_user

CartoDB::Application.routes.draw do
  # Double use: for user public dashboard AND org dashboard
  root :to => 'admin/pages#index'

  get   '(/u/:user_domain)/login'           => 'sessions#new',     as: :login
  get   '(/u/:user_domain)/logout'          => 'sessions#destroy', as: :logout
  match '(/u/:user_domain)/sessions/create' => 'sessions#create',  as: :create_session

  match '/limits' => 'home#limits', as: :limits
  match '/status' => 'home#app_status'

  # OAuth
  match '(/u/:user_domain)/oauth/authorize'      => 'oauth#authorize',     as: :authorize
  match '(/u/:user_domain)/oauth/request_token'  => 'oauth#request_token', as: :request_token
  match '(/u/:user_domain)/oauth/access_token'   => 'oauth#access_token',  as: :access_token
  get   '(/u/:user_domain)/oauth/identity'       => 'sessions#show',       as: :oauth_show_sessions

  get '/google_plus' => 'google_plus#google_plus'
  post '/google/signup' => 'google_plus#google_signup'

  # Internally, some of this methods will forcibly rewrite to the org-url if user belongs to an organization
  scope :module => :admin do

    # Organization dashboard page
    get    '(/u/:user_domain)/organization'                 => 'organizations#show',            as: :organization
    get    '(/u/:user_domain)/organization/settings'        => 'organizations#settings',        as: :organization_settings
    put    '(/u/:user_domain)/organization/settings'        => 'organizations#settings_update', as: :organization_settings_update
    # Organization users management
    get    '(/u/:user_domain)/organization/users/:id/edit'  => 'organization_users#edit',    as: :edit_organization_user,   constraints: { id: /[0-z\.\-]+/ }
    put    '(/u/:user_domain)/organization/users/:id'       => 'organization_users#update',  as: :update_organization_user, constraints: { id: /[0-z\.\-]+/ }
    post   '(/u/:user_domain)/organization/users'           => 'organization_users#create',  as: :create_organization_user
    delete '(/u/:user_domain)/organization/users/:id'       => 'organization_users#destroy', as: :delete_organization_user, constraints: { id: /[0-z\.\-]+/ }
    get    '(/u/:user_domain)/organization/users/new'       => 'organization_users#new',     as: :new_organization_user

    # User profile and account pages
    get    '(/u/:user_domain)/profile' => 'users#profile',        as: :profile_user
    put    '(/u/:user_domain)/profile' => 'users#profile_update', as: :profile_update_user
    get    '(/u/:user_domain)/account' => 'users#account',        as: :account_user
    delete '(/u/:user_domain)/account' => 'users#delete',        as: :account_user
    put    '(/u/:user_domain)/account' => 'users#account_update', as: :account_update_user
    delete '(/u/:user_domain)/account/:id' => 'users#delete', as: :delete_user

    # search
    get '(/u/:user_domain)/dashboard/search/:q'               => 'visualizations#index', as: :search
    get '(/u/:user_domain)/dashboard/search/:q/:page'         => 'visualizations#index', as: :search_page
    get '(/u/:user_domain)/dashboard/shared/search/:q'        => 'visualizations#index', as: :search_shared
    get '(/u/:user_domain)/dashboard/shared/search/:q/:page'  => 'visualizations#index', as: :search_shared_page

    # Tables
    get '(/u/:user_domain)/dashboard/tables'                            => 'visualizations#index', as: :tables_index
    get '(/u/:user_domain)/dashboard/tables/:page'                      => 'visualizations#index', as: :tables_page
    get '(/u/:user_domain)/dashboard/tables/tag/:tag'                   => 'visualizations#index', as: :tables_tag
    get '(/u/:user_domain)/dashboard/tables/tag/:tag/:page'             => 'visualizations#index', as: :tables_tag_page
    get '(/u/:user_domain)/dashboard/tables/shared'                     => 'visualizations#index', as: :tables_shared
    get '(/u/:user_domain)/dashboard/tables/shared/:page'               => 'visualizations#index', as: :tables_shared_page
    get '(/u/:user_domain)/dashboard/tables/shared/tag/:tag'            => 'visualizations#index', as: :tables_shared_tag
    get '(/u/:user_domain)/dashboard/tables/shared/tag/:tag/:page'      => 'visualizations#index', as: :tables_shared_tag_page
    get '(/u/:user_domain)/dashboard/tables/mine'                       => 'visualizations#index', as: :tables_mine
    get '(/u/:user_domain)/dashboard/tables/mine/:page'                 => 'visualizations#index', as: :tables_mine_page
    get '(/u/:user_domain)/dashboard/tables/mine/tag/:tag'              => 'visualizations#index', as: :tables_mine_tag
    get '(/u/:user_domain)/dashboard/tables/mine/tag/:tag/:page'        => 'visualizations#index', as: :tables_mine_tag_page
    get '(/u/:user_domain)/dashboard/tables/mine/locked'                => 'visualizations#index', as: :tables_mine_locked
    get '(/u/:user_domain)/dashboard/tables/mine/locked/:page'          => 'visualizations#index', as: :tables_mine_locked_page
    get '(/u/:user_domain)/dashboard/tables/mine/locked/tag/:tag'       => 'visualizations#index', as: :tables_mine_locked_tag
    get '(/u/:user_domain)/dashboard/tables/mine/locked/tag/:tag/:page' => 'visualizations#index', as: :tables_mine_locked_tag_page
    get '(/u/:user_domain)/dashboard/tables/locked'                     => 'visualizations#index', as: :tables_locked
    get '(/u/:user_domain)/dashboard/tables/locked/:page'               => 'visualizations#index', as: :tables_locked_page
    get '(/u/:user_domain)/dashboard/tables/locked/tag/:tag'            => 'visualizations#index', as: :tables_locked_tag
    get '(/u/:user_domain)/dashboard/tables/locked/tag/:tag/:page'      => 'visualizations#index', as: :tables_locked_tag_page

    # Datasets for new dashboard
    get '(/u/:user_domain)/dashboard/datasets'                              => 'visualizations#index', as: :datasets_index
    get '(/u/:user_domain)/dashboard/datasets/:page'                        => 'visualizations#index', as: :datasets_page
    get '(/u/:user_domain)/dashboard/datasets/tag/:tag'                     => 'visualizations#index', as: :datasets_tag
    get '(/u/:user_domain)/dashboard/datasets/tag/:tag/:page'               => 'visualizations#index', as: :datasets_tag_page
    get '(/u/:user_domain)/dashboard/datasets/shared'                       => 'visualizations#index', as: :datasets_shared
    get '(/u/:user_domain)/dashboard/datasets/shared/:page'                 => 'visualizations#index', as: :datasets_shared_page
    get '(/u/:user_domain)/dashboard/datasets/shared/tag/:tag'              => 'visualizations#index', as: :datasets_shared_tag
    get '(/u/:user_domain)/dashboard/datasets/shared/tag/:tag/:page'        => 'visualizations#index', as: :datasets_shared_tag_page
    get '(/u/:user_domain)/dashboard/datasets/shared/locked'                => 'visualizations#index', as: :datasets_shared_locked
    get '(/u/:user_domain)/dashboard/datasets/shared/locked/:page'          => 'visualizations#index', as: :datasets_shared_locked_page
    get '(/u/:user_domain)/dashboard/datasets/shared/locked/tag/:tag'       => 'visualizations#index', as: :datasets_shared_locked_tag
    get '(/u/:user_domain)/dashboard/datasets/shared/locked/tag/:tag/:page' => 'visualizations#index', as: :datasets_shared_locked_tag_page
    get '(/u/:user_domain)/dashboard/datasets/liked'                        => 'visualizations#index', as: :datasets_liked
    get '(/u/:user_domain)/dashboard/datasets/liked/:page'                  => 'visualizations#index', as: :datasets_liked_page
    get '(/u/:user_domain)/dashboard/datasets/liked/tag/:tag'               => 'visualizations#index', as: :datasets_liked_tag
    get '(/u/:user_domain)/dashboard/datasets/liked/tag/:tag/:page'         => 'visualizations#index', as: :datasets_liked_tag_page
    get '(/u/:user_domain)/dashboard/datasets/liked/locked'                 => 'visualizations#index', as: :datasets_liked_locked
    get '(/u/:user_domain)/dashboard/datasets/liked/locked/:page'           => 'visualizations#index', as: :datasets_liked_locked_page
    get '(/u/:user_domain)/dashboard/datasets/liked/locked/tag/:tag'        => 'visualizations#index', as: :datasets_liked_locked_tag
    get '(/u/:user_domain)/dashboard/datasets/liked/locked/tag/:tag/:page'  => 'visualizations#index', as: :datasets_liked_locked_tag_page
    get '(/u/:user_domain)/dashboard/datasets/locked'                       => 'visualizations#index', as: :datasets_locked
    get '(/u/:user_domain)/dashboard/datasets/locked/:page'                 => 'visualizations#index', as: :datasets_locked_page
    get '(/u/:user_domain)/dashboard/datasets/locked/tag/:tag'              => 'visualizations#index', as: :datasets_locked_tag
    get '(/u/:user_domain)/dashboard/datasets/locked/tag/:tag/:page'        => 'visualizations#index', as: :datasets_locked_tag_page
    get '(/u/:user_domain)/dashboard/datasets/library'                      => 'visualizations#index', as: :datasets_library
    get '(/u/:user_domain)/dashboard/datasets/library/:page'                => 'visualizations#index', as: :datasets_library_page
    get '(/u/:user_domain)/dashboard/datasets/library/tag/:tag'             => 'visualizations#index', as: :datasets_library_tag
    get '(/u/:user_domain)/dashboard/datasets/library/tag/:tag/:page'       => 'visualizations#index', as: :datasets_library_tag_page

    # Tables search
    get '(/u/:user_domain)/dashboard/tables/search/:q'                    => 'visualizations#index', as: :tables_search
    get '(/u/:user_domain)/dashboard/tables/search/:q/:page'              => 'visualizations#index', as: :tables_search_page

app/controllers/admin/organization_users_controller.rb
# coding: utf-8
require_relative '../../../lib/google_plus_api'
require_relative '../../../lib/google_plus_config'

class Admin::OrganizationUsersController < ApplicationController
  ssl_required  :profile, :account, :oauth, :api_key, :regenerate_api_key

  before_filter :get_config
  before_filter :login_required, :check_permissions
  before_filter :get_user, only: [:edit, :update, :destroy]
  before_filter :initialize_google_plus_config, only: [:edit, :update]

  def get_config
    @extras_enabled = extras_enabled?
    @extra_geocodings_enabled = extra_geocodings_enabled?
    @extra_tweets_enabled = extra_tweets_enabled?
  end

  def initialize_google_plus_config
    signup_action = Cartodb::Central.sync_data_with_cartodb_central? ? Cartodb::Central.new.google_signup_url : '/google/signup'
    @google_plus_config = ::GooglePlusConfig.instance(Cartodb.config, signup_action)
  end

  def new
    @user = User.new
    @user.quota_in_bytes = (current_user.organization.unassigned_quota < 100.megabytes ? current_user.organization.unassigned_quota : 100.megabytes)

    new_dashboard = current_user.has_feature_flag?('new_dashboard')
    view =  new_dashboard ? 'create' : 'new'
    layout = new_dashboard ? 'new_application' : 'application'

    respond_to do |format|
      format.html { render view, layout: layout }
    end
  end

  def edit
    set_flash_flags

    new_dashboard = current_user.has_feature_flag?('new_dashboard')
    view =  new_dashboard ? 'new_edit' : 'edit'
    layout = new_dashboard ? 'new_application' : 'application'

    respond_to do |format|
      format.html { render view, layout: layout }
    end
  end

  def set_flash_flags(show_dashboard_details_flash = nil, show_account_settings_flash = nil)
    @show_dashboard_details_flash = session[:show_dashboard_details_flash] || show_dashboard_details_flash
    @show_account_settings_flash = session[:show_account_settings_flash] || show_account_settings_flash
    session[:show_dashboard_details_flash] = nil
    session[:show_account_settings_flash] = nil
  end

  def create
    new_dashboard = current_user.has_feature_flag?('new_dashboard')
    view =  new_dashboard ? 'create' : 'new'
    layout = new_dashboard ? 'new_application' : 'application'

    @user = User.new
    @user.set_fields(params[:user], [:username, :email, :password, :quota_in_bytes, :password_confirmation, :twitter_datasource_enabled])
    @user.organization = current_user.organization
    @user.username = "#{@user.username}"
    copy_account_features(current_user, @user)
    @user.save(raise_on_failure: true)
    @user.create_in_central
    redirect_to organization_path(user_domain: params[:user_domain]), flash: { success: "New user created successfully" }
  rescue CartoDB::CentralCommunicationFailure => e
    Rollbar.report_exception(e)
    begin
      @user.destroy
    rescue => ee
      Rollbar.report_exception(ee)
    end
    set_flash_flags
    flash.now[:error] = e.user_message
    @user = User.new(username: @user.username, email: @user.email, quota_in_bytes: @user.quota_in_bytes, twitter_datasource_enabled: @user.twitter_datasource_enabled)
    render action: view, layout: layout
  rescue Sequel::ValidationFailed => e
    flash.now[:error] = e.message
    render action: view, layout: layout
  end

  def update
    new_dashboard = current_user.has_feature_flag?('new_dashboard')
    view =  new_dashboard ? 'new_edit' : 'edit'
    layout = new_dashboard ? 'new_application' : 'application'

    session[:show_dashboard_details_flash] = params[:show_dashboard_details_flash].present?
    session[:show_account_settings_flash] = params[:show_account_settings_flash].present?

    attributes = params[:user]
    @user.set_fields(attributes, [:email]) if attributes[:email].present? && !@user.google_sign_in
    @user.set_fields(attributes, [:quota_in_bytes]) if current_user.organization_owner?

    @user.set_fields(attributes, [:disqus_shortname]) if attributes[:disqus_shortname].present?
    @user.set_fields(attributes, [:available_for_hire]) if attributes[:available_for_hire].present?
    @user.set_fields(attributes, [:name]) if attributes[:name].present?
    @user.set_fields(attributes, [:website]) if attributes[:website].present?
    @user.set_fields(attributes, [:description]) if attributes[:description].present?
    @user.set_fields(attributes, [:twitter_username]) if attributes[:twitter_username].present?

    @user.password = attributes[:password] if attributes[:password].present?
    @user.password_confirmation = attributes[:password_confirmation] if attributes[:password_confirmation].present?
    @user.soft_geocoding_limit = attributes[:soft_geocoding_limit] if attributes[:soft_geocoding_limit].present?
    @user.twitter_datasource_enabled = attributes[:twitter_datasource_enabled] if attributes[:twitter_datasource_enabled].present?
    @user.soft_twitter_datasource_limit = attributes[:soft_twitter_datasource_limit] if attributes[:soft_twitter_datasource_limit].present?
    @user.update_in_central

    @user.save(raise_on_failure: true)

    redirect_to edit_organization_user_path(user_domain: params[:user_domain], id: @user.username), flash: { success: "Updated successfully" }
  rescue CartoDB::CentralCommunicationFailure => e
    set_flash_flags
    flash.now[:error] = "There was a problem while updating this user. Please, try again and contact us if the problem persists. #{e.user_message}"
    render action: view, layout: layout
  rescue Sequel::ValidationFailed => e
    render action: view, layout: layout
  end

  def destroy
    new_dashboard = current_user.has_feature_flag?('new_dashboard')
    @user.delete_in_central
    @user.destroy
    flash[:success] = "User was successfully deleted."
    if new_dashboard
      redirect_to organization_path(user_domain: params[:user_domain])
    else
      head :no_content
    end
  rescue CartoDB::CentralCommunicationFailure => e
    Rollbar.report_exception(e)
    if e.user_message =~ /No user found with username/
      @user.destroy
      flash[:success] = "User was deleted from the organization server. #{e.user_message}"
      if new_dashboard
        redirect_to organization_path(user_domain: params[:user_domain])
      else
        head :no_content
      end
    else
      set_flash_flags(nil, true)
      flash[:error] = "User was not deleted. #{e.user_message}"
      head :no_content
    end
  end

  def extras_enabled?
    extra_geocodings_enabled? || extra_tweets_enabled?
  end

  def extra_geocodings_enabled?
    !Cartodb.get_config(:geocoder, 'app_id').blank?
  end

  def extra_tweets_enabled?
    !Cartodb.get_config(:datasource_search, 'twitter_search', 'standard', 'username').blank?
  end

  private

  def check_permissions
    raise RecordNotFound unless current_user.organization.present?
    raise RecordNotFound unless current_user.organization_owner? || ['edit', 'update'].include?(params[:action])
  end

  def get_user
    @user = current_user.organization.users_dataset.where(username: params[:id]).first
    raise RecordNotFound unless @user
    raise RecordNotFound unless current_user.organization_owner? || current_user == @user
  end

  def copy_account_features(from, to)
    to.set_fields(from, [
      :private_tables_enabled, :sync_tables_enabled, :max_layers, :user_timeout,
      :database_timeout, :geocoding_quota, :map_view_quota, :table_quota, :database_host,
      :period_end_date, :map_view_block_price, :geocoding_block_price, :account_type,
      :twitter_datasource_enabled, :soft_twitter_datasource_limit, :twitter_datasource_quota,
      :twitter_datasource_block_price, :twitter_datasource_block_size
    ])
    to.invite_token = User.make_token
  end
end

app/views/admin/organization_users/_new_form.html.erb
<%= form_for @user, url: (@user.new? ? create_organization_user_path(user_domain: params[:user_domain], id: @organization) : update_organization_user_path(user_domain: params[:user_domain], id: @user.username)), :class =>'Form' do |f| %>

  <%= f.hidden_field :private_tables_enabled %>
  <%= hidden_field_tag :show_account_settings_flash, true %>
  <%= csrf_meta_tags %>

  <div class="Form-title">
    <% if !@user.new? %>
      <p class="Form-titleText">Edit <%= @user.username %> user from your <%= current_user.organization.name %> organization.</p>
    <% else %>
      <p class="Form-titleText">Create a new user for your <%= current_user.organization.name %> organization.
      <% if !Cartodb.config[:cartodb_com_hosted].present? %>
        If you need more resources, don't hesitate to <a href="mailto:support@cartodb.com">contact us</a>.
      <% end %>
      </p>
    <% end %>
  </div>

  <div class="Form-row">
    <div class="Form-rowLabel">
      <label class="Form-label">User name</label>
    </div>
    <div class="Form-rowData Form-rowData--med">
      <%= f.text_field :username, :class => "Form-input Form-input--med #{ 'is-disabled' if !@user.new? } #{ 'Form-input--error' if @user.errors[:username].present? }", :readonly => !@user.new? %>
    </div>
    <div class="Form-rowInfo">
      <% if (@user.errors[:username].present?) %>
        <p class="Form-rowInfoText Form-rowInfoText--error">Username not valid</p>
      <% elsif !@user.new? %>
        <p class="Form-rowInfoText">You enter through <%= link_to 'here', @user.public_url %></p>
      <% else %>
        <p class="Form-rowInfoText">Once you choose the username, you won't be able to change it</p>
      <% end %>
    </div>
  </div>

  <div class="Form-row">
    <div class="Form-rowLabel">
      <label class="Form-label">User email</label>
    </div>
    <div class="Form-rowData Form-rowData--med">
      <%= f.text_field :email, :class => "Form-input Form-input--med #{ 'is-disabled' if !@user.can_change_email } #{ 'Form-input--error' if @user.errors[:email].present? }", readonly: !@user.can_change_email %>
    </div>
    <div class="Form-rowInfo">
      <% if (@user.errors[:email].present?) %>
        <p class="Form-rowInfoText Form-rowInfoText--error">Email not valid</p>
      <% elsif @user.new? %>
        <p class="Form-rowInfoText">We encourage you to choose an email from your organization</p>
      <% end %>
    </div>
  </div>

  <div class="Form-row">
    <div class="Form-rowLabel">
      <label class="Form-label">User password</label>
    </div>
    <div class="Form-rowData Form-rowData--med">
      <%= password_field_tag 'user[password]', nil, :placeholder => "new password", :class => "Form-input Form-input--short #{ 'Form-input--error' if @user.errors[:password].present? }" %>
      <%= password_field_tag 'user[password_confirmation]', nil, :placeholder => "confirm new one", :class => "Form-input Form-input--short #{ 'hello' if @user.errors[:password].present?}" %>
    </div>
    <div class="Form-rowInfo">
      <% if (@user.errors[:password].present?) %>
        <p class="Form-rowInfoText Form-rowInfoText--error">Password not valid</p>
      <% else %>
        <p class="Form-rowInfoText">Password should be 6 characters at least</p>
      <% end %>
    </div>
  </div>

  <div class="Form-row">
    <div class="Form-rowLabel">
      <label class="Form-label">User quota</label>
    </div>
    <div class="OrganizationUser-quota js-quota">
      <div class="Form-rowData Form-rowData--med OrganizationUser-quotaProgress js-quotaProgress">
        <div class="progress-bar OrganizationUser-quotaBar">
          <% assignedPer = ((@user.quota_in_bytes.to_f * 100) / current_user.organization.quota_in_bytes) %>
          <span class="bar-2 js-assignedBar" style="width:<%= assignedPer %>%"></span>
          <% if !@user.new? %>
            <% usedPer = ((@user.db_size_in_bytes.to_f * 100) / current_user.organization.quota_in_bytes) %>
            <span class="bar-3" style="width:<%= usedPer %>%"></span>
          <% end %>
        </div>
        <ul class="OrganizationUser-quotaLegend">
          <% if !@user.new? %>
            <li class="OrganizationUser-quotaLegendItem">
              <i class="OrganizationUser-quotaLegendIcon OrganizationUser-quotaLegendIcon--used"></i>
              Used by user
            </li>
          <% end %>
          <li class="OrganizationUser-quotaLegendItem">
            <i class="OrganizationUser-quotaLegendIcon OrganizationUser-quotaLegendIcon--assigned"></i>
            Assigned to user
          </li>
          <li class="OrganizationUser-quotaLegendItem">
            <i class="OrganizationUser-quotaLegendIcon"></i>
            Total
          </li>
        </ul>
      </div>
      <div class="Form-rowInfo OrganizationUser-quotaInfo js-quotaInfo">
        <span class="js-assignedSize"><%= number_to_human_size(@user.quota_in_bytes) %></span> assigned, <button class="OrganizationUser-quotaInfoLink js-changeQuota">change</button> or <a href="<%= current_user.upgrade_url(request.protocol) %>">upgrade your account</a> if needed
      </div>
      <%= f.hidden_field :quota_in_bytes, :id => "user_quota" %>
    </div>
  </div>

  <div class="Form-row">
    <div class="Form-rowLabel">
      <label class="Form-label">Extra geocoding</label>
    </div>
    <div class="Form-rowData Form-rowData--med">
      <div class="Toggler">
        <%= f.check_box :soft_geocoding_limit, :id => "soft_geocoding_limit" %>
        <%= label_tag(:soft_geocoding_limit, '') %>
      </div>
    </div>
    <div class="Form-rowInfo">
      <p class="Form-rowInfoText">User has permission to exceed organization's geocoding quota</p>
    </div>
  </div>

  <div class="Form-row">
    <div class="Form-rowLabel">
      <label class="Form-label">Extra tweets</label>
    </div>
    <div class="Form-rowData Form-rowData--med">
      <div class="Toggler">
        <%= f.check_box :soft_twitter_datasource_limit, :id => "soft_twitter_datasource_limit" %>
        <%= label_tag(:soft_twitter_datasource_limit, '') %>
      </div>
    </div>
    <div class="Form-rowInfo">
      <p class="Form-rowInfoText">User has permission to exceed organization's Twitter credits</p>
    </div>
  </div>

  <div class="Form-footer">
    <% if !@user.new? && current_user.organization_owner? -%>
      <% if @user != current_user %>
        <button href="<%= delete_organization_user_path(user_domain: params[:user_domain], id: @user.username) %>" class="Button Button--secondary js-deleteAccount">
          <span>Delete this user</span>
        </button>
      <% else %>
        <em></em>
      <% end %>
      <button type="submit" class="Button Button--main">
        <span>Save changes</span>
      </button>
    <% else %>
      <em></em>
      <button type="submit" class="Button Button--main">
        <span>Create user</span>
      </button>
    <% end %>
  </div>

<% end %>

<script type="text/javascript">
  <% if !@user.new? %>
    var organization_user_data = <%= raw @user.data.to_json.html_safe -%>;
  <% end %>
  <%
    assigned_quota_in_bytes = 0
    current_user.organization.users.map { |u| 
      assigned_quota_in_bytes = assigned_quota_in_bytes + u.quota_in_bytes 
    }
  %>
  var assigned_user_quota = <%= @user.quota_in_bytes %>;
  var used_user_quota = <%= @user.db_size_in_bytes rescue 0 %>;
  var user_name = "<%= @user.username %>";
  var organization_data = {
    quota_in_bytes: <%= current_user.organization.quota_in_bytes %>,
    used_quota_in_bytes: <%= assigned_quota_in_bytes %>
  };
</script>

app/views/admin/organization_users/create.html.erb
<% content_for(:page_title) do %>
  New <%= current_user.organization.name %> user |
<% end %>
<%= content_for(:js) do %>
  <script type="text/javascript">
    var username = "<%= current_user.username %>";
    var config = <%=raw frontend_config.html_safe %>;
    var user_data = <%= raw current_user.data.to_json.html_safe %>;
  </script>
  <%= javascript_include_tag 'cdb.js', 'models.js', 'new_organization_templates.js', 'new_organization_deps.js', 'new_organization.js' -%>
<% end %>
<%= content_for(:css) do %>
  <%= stylesheet_link_tag 'new_organization.css',  :media => 'all' %>
<% end %>

<%= render :partial => 'shared/new_flash_message' %>

<div>
  <div class="Filters is-relative">
    <div class="u-inner">
      <div class="Filters-inner">
        <span class="Filters-separator"></span>
        <div class="Filters-row">
          <div class="Filters-type">
            <ul class="Filters-list">
              <li>
                <a href="<%= organization_url(user_domain: params[:user_domain]) %>" class="Filters-typeLink Filters-actionButton NavButton NavButton--back">
                  <i class="iconFont iconFont-ArrowPrev"></i>
                </a>
              </li>
              <li class="Filters-typeItem"><a class="Filters-typeLink is-selected">New user</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="OrganizationContent">
    <div class="u-inner">
      <%= render partial: 'new_form' %>
    </div>
  </div>
</div>

<% if !Cartodb.config[:cartodb_com_hosted].present? %>
  <div class="SupportBanner" id="support-banner"></div>
<% end %>

<%= render 'admin/shared/new_footer' %>

app/views/admin/organization_users/new.html.erb
<% content_for(:page_title) do %>
  Add a new user |
<% end %>
<%= content_for(:js) do %>
  <%= javascript_include_tag 'cdb.js', 'application.js', 'models.js', 'organization.js', 'templates.js' %>
  <script type="text/javascript">
    var username = "<%= current_user.username %>"
      , type = "oauth"
      , config = <%=raw frontend_config.html_safe %>
      , organization_quota = {
          seats: <%= current_user.organization.seats %>,
          quota_in_bytes: <%= current_user.organization.quota_in_bytes %>
        }
      , user_data = <%=raw current_user.data.to_json.html_safe %>;
  </script>
<% end %>
<%= content_for(:css) do %>
  <%= stylesheet_link_tag 'common.css', 'organization.css', :media => 'all' %>
<% end %>

<%= content_for(:account_settings) do %>
  <%= render partial: "admin/organizations/settings_account" %>
<% end %>

<ul><%= render :partial => 'shared/flash_message' %></ul>

<article>
  <div class="inner">
    <%= render partial: 'form' %>
  </div>
</article>