config/routes.rb
# encoding: utf-8

# NOTES:
# (/u/:user_domain)                -> This allows support of org-urls (support != enforcement)
# defaults: { dont_rewrite: true } -> Use this to force an individual action to not get rewritten to org-url
# Can be also done at controller source files by using -> skip_before_filter :ensure_org_url_if_org_user

CartoDB::Application.routes.draw do
  # Double use: for user public dashboard AND org dashboard
  root :to => 'admin/pages#index'

  get   '(/u/:user_domain)/login'           => 'sessions#new',     as: :login
  get   '(/u/:user_domain)/logout'          => 'sessions#destroy', as: :logout
  match '(/u/:user_domain)/sessions/create' => 'sessions#create',  as: :create_session

  match '/limits' => 'home#limits', as: :limits
  match '/status' => 'home#app_status'

  # OAuth
  match '(/u/:user_domain)/oauth/authorize'      => 'oauth#authorize',     as: :authorize
  match '(/u/:user_domain)/oauth/request_token'  => 'oauth#request_token', as: :request_token
  match '(/u/:user_domain)/oauth/access_token'   => 'oauth#access_token',  as: :access_token
  get   '(/u/:user_domain)/oauth/identity'       => 'sessions#show',       as: :oauth_show_sessions

  get '/google_plus' => 'google_plus#google_plus'
  post '/google/signup' => 'google_plus#google_signup'

  # Internally, some of this methods will forcibly rewrite to the org-url if user belongs to an organization
  scope :module => :admin do

    # Organization dashboard page
    get    '(/u/:user_domain)/organization'                 => 'organizations#show',            as: :organization
    get    '(/u/:user_domain)/organization/settings'        => 'organizations#settings',        as: :organization_settings
    put    '(/u/:user_domain)/organization/settings'        => 'organizations#settings_update', as: :organization_settings_update
    # Organization users management
    get    '(/u/:user_domain)/organization/users/:id/edit'  => 'organization_users#edit',    as: :edit_organization_user,   constraints: { id: /[0-z\.\-]+/ }
    put    '(/u/:user_domain)/organization/users/:id'       => 'organization_users#update',  as: :update_organization_user, constraints: { id: /[0-z\.\-]+/ }
    post   '(/u/:user_domain)/organization/users'           => 'organization_users#create',  as: :create_organization_user
    delete '(/u/:user_domain)/organization/users/:id'       => 'organization_users#destroy', as: :delete_organization_user, constraints: { id: /[0-z\.\-]+/ }
    get    '(/u/:user_domain)/organization/users/new'       => 'organization_users#new',     as: :new_organization_user

    # User profile and account pages
    get    '(/u/:user_domain)/profile' => 'users#profile',        as: :profile_user
    put    '(/u/:user_domain)/profile' => 'users#profile_update', as: :profile_update_user
    get    '(/u/:user_domain)/account' => 'users#account',        as: :account_user
    delete '(/u/:user_domain)/account' => 'users#delete',        as: :account_user
    put    '(/u/:user_domain)/account' => 'users#account_update', as: :account_update_user
    delete '(/u/:user_domain)/account/:id' => 'users#delete', as: :delete_user

    # search
    get '(/u/:user_domain)/dashboard/search/:q'               => 'visualizations#index', as: :search
    get '(/u/:user_domain)/dashboard/search/:q/:page'         => 'visualizations#index', as: :search_page
    get '(/u/:user_domain)/dashboard/shared/search/:q'        => 'visualizations#index', as: :search_shared
    get '(/u/:user_domain)/dashboard/shared/search/:q/:page'  => 'visualizations#index', as: :search_shared_page

    # Tables
    get '(/u/:user_domain)/dashboard/tables'                            => 'visualizations#index', as: :tables_index
    get '(/u/:user_domain)/dashboard/tables/:page'                      => 'visualizations#index', as: :tables_page
    get '(/u/:user_domain)/dashboard/tables/tag/:tag'                   => 'visualizations#index', as: :tables_tag
    get '(/u/:user_domain)/dashboard/tables/tag/:tag/:page'             => 'visualizations#index', as: :tables_tag_page
    get '(/u/:user_domain)/dashboard/tables/shared'                     => 'visualizations#index', as: :tables_shared
    get '(/u/:user_domain)/dashboard/tables/shared/:page'               => 'visualizations#index', as: :tables_shared_page
    get '(/u/:user_domain)/dashboard/tables/shared/tag/:tag'            => 'visualizations#index', as: :tables_shared_tag
    get '(/u/:user_domain)/dashboard/tables/shared/tag/:tag/:page'      => 'visualizations#index', as: :tables_shared_tag_page
    get '(/u/:user_domain)/dashboard/tables/mine'                       => 'visualizations#index', as: :tables_mine
    get '(/u/:user_domain)/dashboard/tables/mine/:page'                 => 'visualizations#index', as: :tables_mine_page
    get '(/u/:user_domain)/dashboard/tables/mine/tag/:tag'              => 'visualizations#index', as: :tables_mine_tag
    get '(/u/:user_domain)/dashboard/tables/mine/tag/:tag/:page'        => 'visualizations#index', as: :tables_mine_tag_page
    get '(/u/:user_domain)/dashboard/tables/mine/locked'                => 'visualizations#index', as: :tables_mine_locked
    get '(/u/:user_domain)/dashboard/tables/mine/locked/:page'          => 'visualizations#index', as: :tables_mine_locked_page
    get '(/u/:user_domain)/dashboard/tables/mine/locked/tag/:tag'       => 'visualizations#index', as: :tables_mine_locked_tag
    get '(/u/:user_domain)/dashboard/tables/mine/locked/tag/:tag/:page' => 'visualizations#index', as: :tables_mine_locked_tag_page
    get '(/u/:user_domain)/dashboard/tables/locked'                     => 'visualizations#index', as: :tables_locked
    get '(/u/:user_domain)/dashboard/tables/locked/:page'               => 'visualizations#index', as: :tables_locked_page
    get '(/u/:user_domain)/dashboard/tables/locked/tag/:tag'            => 'visualizations#index', as: :tables_locked_tag
    get '(/u/:user_domain)/dashboard/tables/locked/tag/:tag/:page'      => 'visualizations#index', as: :tables_locked_tag_page

    # Datasets for new dashboard
    get '(/u/:user_domain)/dashboard/datasets'                              => 'visualizations#index', as: :datasets_index
    get '(/u/:user_domain)/dashboard/datasets/:page'                        => 'visualizations#index', as: :datasets_page
    get '(/u/:user_domain)/dashboard/datasets/tag/:tag'                     => 'visualizations#index', as: :datasets_tag
    get '(/u/:user_domain)/dashboard/datasets/tag/:tag/:page'               => 'visualizations#index', as: :datasets_tag_page
    get '(/u/:user_domain)/dashboard/datasets/shared'                       => 'visualizations#index', as: :datasets_shared
    get '(/u/:user_domain)/dashboard/datasets/shared/:page'                 => 'visualizations#index', as: :datasets_shared_page
    get '(/u/:user_domain)/dashboard/datasets/shared/tag/:tag'              => 'visualizations#index', as: :datasets_shared_tag
    get '(/u/:user_domain)/dashboard/datasets/shared/tag/:tag/:page'        => 'visualizations#index', as: :datasets_shared_tag_page
    get '(/u/:user_domain)/dashboard/datasets/shared/locked'                => 'visualizations#index', as: :datasets_shared_locked
    get '(/u/:user_domain)/dashboard/datasets/shared/locked/:page'          => 'visualizations#index', as: :datasets_shared_locked_page
    get '(/u/:user_domain)/dashboard/datasets/shared/locked/tag/:tag'       => 'visualizations#index', as: :datasets_shared_locked_tag
    get '(/u/:user_domain)/dashboard/datasets/shared/locked/tag/:tag/:page' => 'visualizations#index', as: :datasets_shared_locked_tag_page
    get '(/u/:user_domain)/dashboard/datasets/liked'                        => 'visualizations#index', as: :datasets_liked
    get '(/u/:user_domain)/dashboard/datasets/liked/:page'                  => 'visualizations#index', as: :datasets_liked_page
    get '(/u/:user_domain)/dashboard/datasets/liked/tag/:tag'               => 'visualizations#index', as: :datasets_liked_tag
    get '(/u/:user_domain)/dashboard/datasets/liked/tag/:tag/:page'         => 'visualizations#index', as: :datasets_liked_tag_page
    get '(/u/:user_domain)/dashboard/datasets/liked/locked'                 => 'visualizations#index', as: :datasets_liked_locked
    get '(/u/:user_domain)/dashboard/datasets/liked/locked/:page'           => 'visualizations#index', as: :datasets_liked_locked_page
    get '(/u/:user_domain)/dashboard/datasets/liked/locked/tag/:tag'        => 'visualizations#index', as: :datasets_liked_locked_tag
    get '(/u/:user_domain)/dashboard/datasets/liked/locked/tag/:tag/:page'  => 'visualizations#index', as: :datasets_liked_locked_tag_page
    get '(/u/:user_domain)/dashboard/datasets/locked'                       => 'visualizations#index', as: :datasets_locked
    get '(/u/:user_domain)/dashboard/datasets/locked/:page'                 => 'visualizations#index', as: :datasets_locked_page
    get '(/u/:user_domain)/dashboard/datasets/locked/tag/:tag'              => 'visualizations#index', as: :datasets_locked_tag
    get '(/u/:user_domain)/dashboard/datasets/locked/tag/:tag/:page'        => 'visualizations#index', as: :datasets_locked_tag_page
    get '(/u/:user_domain)/dashboard/datasets/library'                      => 'visualizations#index', as: :datasets_library
    get '(/u/:user_domain)/dashboard/datasets/library/:page'                => 'visualizations#index', as: :datasets_library_page
    get '(/u/:user_domain)/dashboard/datasets/library/tag/:tag'             => 'visualizations#index', as: :datasets_library_tag
    get '(/u/:user_domain)/dashboard/datasets/library/tag/:tag/:page'       => 'visualizations#index', as: :datasets_library_tag_page

    # Tables search
    get '(/u/:user_domain)/dashboard/tables/search/:q'                    => 'visualizations#index', as: :tables_search
    get '(/u/:user_domain)/dashboard/tables/search/:q/:page'              => 'visualizations#index', as: :tables_search_page

app/models/client_application.rb
# coding: utf-8
require 'oauth'

class ClientApplication < Sequel::Model

  one_to_many :tokens, :class_name => :OauthToken
  one_to_many :access_tokens
  one_to_many :oauth_tokens
  
  plugin :association_dependencies
  add_association_dependencies :oauth_tokens => :destroy

  attr_accessor :token_callback_url

  def self.find_token(token_key)
    return nil if token_key.nil?
    token = ::RequestToken.first(:token => token_key) || ::AccessToken.first(:token => token_key)
    token && token.authorized? ? token : nil
  end

  def self.find_by_key(key)
    first(:key => key)
  end

  def user
    User[user_id]
  end

  def user=(value)
    set(:user_id => value.id)
  end

  def self.verify_request(request, options = {}, &block)
    begin
      signature = OAuth::Signature.build(request, options, &block)
      # As we're always over SSL the extra Nonce security is not really needed so we gain performance and
      # we avoid storing every nonce in redis as well (for node).
      # return false unless OauthNonce.remember(signature.request.nonce, signature.request.timestamp)
      value = signature.verify
      value
    rescue OAuth::Signature::UnknownSignatureMethod => e
      false
    end
  end
  
  def oauth_server
    @oauth_server ||= OAuth::Server.new("http://your.site")
  end

  def credentials
    @oauth_client ||= OAuth::Consumer.new(key, secret)
  end

  # If your application requires passing in extra parameters handle it here
  def create_request_token(params={})
    RequestToken.create :client_application => self, :callback_url=>self.token_callback_url
  end

  def before_create
    self.key        = OAuth::Helper.generate_key(40)[0,40]
    self.secret     = OAuth::Helper.generate_key(40)[0,40]
    self.created_at = Time.now
  end

  def before_save
    self.updated_at = Time.now
  end
end

app/controllers/admin/client_applications_controller.rb
# coding: utf-8

class Admin::ClientApplicationsController < ApplicationController
  ssl_required :oauth, :api_key, :regenerate_api_key

  before_filter :login_required

  def oauth
    new_dashboard = current_user.has_feature_flag?('new_dashboard')
    view =  new_dashboard ? 'new_oauth' : 'api_key'
    layout = new_dashboard ? 'new_application' : 'application'

    respond_to do |format|
      format.html { render view, layout: layout }
    end
  end

  def api_key
    new_dashboard = current_user.has_feature_flag?('new_dashboard')
    view =  new_dashboard ? 'new_api_key' : 'api_key'
    layout = new_dashboard ? 'new_application' : 'application'

    respond_to do |format|
      format.html { render view, layout: layout }
    end
  end

  def regenerate_api_key
    begin
      current_user.invalidate_varnish_cache
      current_user.update api_key: User.make_token
      flash_message = "Your API key has been successfully generated"
    rescue Errno::ECONNREFUSED => e
      CartoDB::Logger.info "Could not clear varnish cache", "#{e.inspect}"
      if Rails.env.development?
        current_user.set_map_key
        flash_message = "Your API key has been regenerated succesfully but the varnish cache has not been invalidated."
      else
        raise e
      end
    rescue => e
      raise e
    end 
    redirect_to api_key_credentials_path(user_domain: params[:user_domain], type: 'api_key'), :flash => {:success => "Your API key has been regenerated successfully"}
  end

  def regenerate_oauth
    @client_application = current_user.client_application
    return if request.get?
    current_user.reset_client_application!
    
    new_dashboard = current_user.has_feature_flag?('new_dashboard')
    if new_dashboard
      redirect_to oauth_credentials_path(user_domain: params[:user_domain], type: 'oauth'), :flash => {:success => "Your OAuth credentials have been updated successfully"}
    else
      redirect_to api_key_credentials_path(user_domain: params[:user_domain], type: 'oauth'), :flash => {:success => "Your OAuth credentials have been updated successfully"}
    end 
    
  end

end

app/views/admin/client_applications/api_key.html.erb
<% content_for(:page_title) do %>
  Your apps |
<% end %>
<%= content_for(:js) do %>
  <script type="text/javascript">
    var username = "<%= current_user.username %>"
      , config = <%=raw frontend_config.html_safe %>
      , user_data = <%= raw current_user.data.to_json.html_safe %>;
  </script>
  <%= javascript_include_tag 'cdb.js', 'application.js', 'models.js', 'keys.js', 'templates.js' %>
<% end %>
<%= content_for(:css) do %>
  <%= stylesheet_link_tag 'common.css', 'keys.css', :media => 'all' %>
<% end %>

<article class="api_key">
  <div class="inner">
    <section class="block">
      <div class="head">
        <h3>Your Api key</h3>
        <p class="margin10 light">This offers the simplest way to access your private data or perform writes and updates to your account.</p>
      </div>
      <% if params[:type] == "api_key" %>
        <ul><%= render :partial => 'shared/flash_message' %></ul>
      <% end %>
      <div class="content">
        <ul>
          <li>
            <form>
              <div class="column left-column">

                <div class="row">
                  <div class="field copy field-1">
                    <label>YOUR API KEY</label>
                    <input type="text" readonly value="<%= current_user.api_key || "No api key" %>" />
                    <a class="tooltip copy" href="#/copy" title="Copy this">copy</a>
                  </div>
                </div>

                <div class="row">
                  <div class="field field-1">
                    <label><strong>Example write:</strong></label>
                    <p class="small italic">http://<%= current_user.username %>.cartodb.com/api/v2/sql?q=INSERT INTO table_name (the_geom, observation) VALUES (ST_GeomFromText(’POINT(-71.2 42.5)’, 4326),'rare bird spotted')&api_key=<%= current_user.api_key %></p>
                  </div>
                </div>

                <div class="row">
                  <div class="field field-1">
                    <label><strong>Example private table read:</strong></label>
                    <p class="small italic">http://<%= current_user.username %>.cartodb.com/api/v2/sql?q=SELECT * FROM private_table&api_key=<%= current_user.api_key %></p>
                  </div>
                </div>

              </div>
              <div class="coloumn right-column">
                <div class="row">
                  <p>Learn more about <%= link_to "using your simple app key", Cartodb.config[:developers_host] + "/documentation/apis-overview.html" %> in CartoDB</p>
                </div>
              </div>
            </form>
          </li>
        </ul>
      </div>
      <div class="foot">
        <%= form_tag(regenerate_api_key_url(user_domain: params[:user_domain]), :method => "POST", :id => 'regenerate_api_key') do %>
          <%= link_to "Request a new api key", "#/request-api-key", :class => "right underline red regenerate", :data => { :type => "keys" } %>
        <% end %>
      </div>
    </section>
  </div>
</article>

<article class="oauth">
  <div class="inner">
    <section class="block">
      <div class="head">
        <h3>Your OAuth credentials</h3>
        <p class="margin10 light">OAuth is an authentication protocol that allows users to approve application to act on their behalf without sharing their password.</p>
      </div>
      <% if params[:type] == "oauth" %>
        <ul><%= render :partial => 'shared/flash_message' %></ul>
      <% end %>
      <div class="content">
        <ul>
          <li>
            <form>
              <div class="column left-column">

                <div class="row">
                  <div class="field copy field-1 copy">
                    <label>CONSUMER KEY</label>
                    <input type="text" value="<%= current_user.client_application.key %>" readonly />
                    <a class="tooltip copy" href="#/copy" title="Copy this">copy</a>
                  </div>
                </div>

                <div class="row">
                  <div class="field field-1 copy">
                    <label class="uppercase smaller strong lighter">CONSUMER SECRET</label>
                    <input type="text" value="<%= current_user.client_application.secret %>" readonly />
                    <a class="copy tooltip" href="#/copy" title="Copy this">copy</a>
                  </div>
                </div>

                <span class="separate"></span>

                <div class="row">
                  <div class="field field-1 copy">
                    <label>REQUEST TOKEN URL</label>
                    <input type="text" value="https://<%= current_user.username %>.cartodb.com/oauth/request_token" readonly />
                    <a class="copy tooltip" href="#/copy" title="Copy this">copy</a>
                  </div>
                </div>

                <div class="row">
                  <div class="field field-1 copy">
                    <label>ACCESS TOKEN URL</label>
                    <input type="text" value="https://<%= current_user.username %>.cartodb.com/oauth/access_token" readonly />
                    <a class="copy tooltip" href="#/copy" title="Copy this">copy</a>
                  </div>
                </div>

              </div>
              <div class="coloumn right-column">
                <div class="row">
                  <p>Learn more about <%= link_to "using oauth in CartoDB", Cartodb.config[:developers_host] + "/documentation/sql-api.html#authentication" %> in CartoDB</p>
                </div>
              </div>
            </form>
          </li>
        </ul>
      </div>
      <div class="foot">
        <%= form_tag(regenerate_oauth_url(user_domain: params[:user_domain]), :method => "DELETE", :id => 'regenerate_oauth_keys') do %>
          <%= link_to "Request new oauth keys", "#/request-new-keys", :class => "right underline red regenerate", :data => { :type => "oauth" } %>
        <% end %>
      </div>
    </section>
  </div>
</article>

app/views/admin/client_applications/new_api_key.html.erb
<% content_for(:page_title) do %>
  Your API keys |
<% end %>
<%= content_for(:js) do %>
  <script type="text/javascript">
    var username = "<%= current_user.username %>";
    var config = <%=raw frontend_config.html_safe %>;
    var user_data = <%= raw current_user.data.to_json.html_safe %>;
  </script>
  <%= javascript_include_tag 'cdb.js', 'models.js', 'new_keys_templates.js', 'new_keys_deps.js', 'new_keys.js' -%>
<% end %>
<%= content_for(:css) do %>
  <%= stylesheet_link_tag 'new_keys.css', :media => 'all' %>
<% end %>

<div>

  <%= render :partial => 'admin/shared/new_pages_subheader' %>

  <div class="CredentialsContent">
    <div class="u-inner">
      <%= form_tag(regenerate_api_key_url(user_domain: params[:user_domain]), :method => "POST", :id => 'regenerate_api_key', :class => 'Form') do %>

        <div class="Form-title">
          <p class="Form-titleText">This offers the simplest way to access your private data or perform writes and updates to your account.</p>
        </div>

        <div class="Form-row Form-row--spaced">
          <div class="Form-rowLabel">
            <label class="Form-label">Your API Key</label>
          </div>
          <div class="Form-rowData">
            <input type="text" class="Form-input Form-input--long has-icon js-input" placeholder="No API key" value="<%= current_user.api_key %>" readonly />
            <i data-title="Copy this" class="iconFont iconFont-Anchor Form-inputIcon Form-copyIcon js-copy-value"></i>
          </div>
        </div>

        <span class="Form-separator"></span>

        <div class="Form-row Form-row--spaced">
          <div class="Form-rowLabel">
            <label class="Form-label">Example write</label>
          </div>
          <div class="Form-rowPreview">
            <p class="Form-text Form-text--preview">http://<%= current_user.username %>.<%= Cartodb.config[:account_host] %>/api/v2/sql?q=INSERT INTO table_name (the_geom, observation) VALUES (ST_GeomFromText(’POINT(-71.2 42.5)’, 4326),'rare bird spotted')&api_key=<%= current_user.api_key %></p>
          </div>
        </div>

        <div class="Form-row Form-row--spaced">
          <div class="Form-rowLabel">
            <label class="Form-label">Example read private</label>
          </div>
          <div class="Form-rowPreview">
            <p class="Form-text Form-text--preview">http://<%= current_user.username %>.<%= Cartodb.config[:account_host] %>/api/v2/sql?q=SELECT * FROM private_table&api_key=<%= current_user.api_key %></p>
          </div>
        </div>

        <div class="Form-footer">
          <p class="Form-footerText">
            <i class="iconFont iconFont-Info Form-footerIcon"></i>
            Learn more about <%= link_to "using your simple app key", Cartodb.config[:developers_host] + "/cartodb-platform.html" %> in CartoDB
          </p>
          <%= button_tag(type: 'submit', class: 'Button Button--main js-submit', value: 'api') do %>
            <% content_tag(:span, 'Request a new api key') %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

</div>

<% if !Cartodb.config[:cartodb_com_hosted].present? %>
  <div class="SupportBanner" id="support-banner"></div>
<% end %>

<%= render 'admin/shared/new_footer' %>

app/views/admin/client_applications/new_oauth.html.erb
<% content_for(:page_title) do %>
  Your OAuth credentials |
<% end %>
<%= content_for(:js) do %>
  <script type="text/javascript">
    var username = "<%= current_user.username %>";
    var config = <%=raw frontend_config.html_safe %>;
    var user_data = <%= raw current_user.data.to_json.html_safe %>;
  </script>
  <%= javascript_include_tag 'cdb.js', 'models.js', 'new_keys_templates.js', 'new_keys_deps.js', 'new_keys.js' -%>
<% end %>
<%= content_for(:css) do %>
  <%= stylesheet_link_tag 'new_keys.css', :media => 'all' %>
<% end %>

<div>

  <%= render :partial => 'admin/shared/new_pages_subheader' %>

  <div class="CredentialsContent">
    <div class="u-inner">
      <%= form_tag(regenerate_oauth_url(user_domain: params[:user_domain]), :method => "DELETE", :id => 'regenerate_oauth_keys', :class => "Form") do %>

        <div class="Form-title">
          <p class="Form-titleText">OAuth is an authentication protocol that allows users to approve application to act on their behalf without sharing their password.</p>
        </div>

        <div class="Form-row">
          <div class="Form-rowLabel">
            <label class="Form-label">Consumer key</label>
          </div>
          <div class="Form-rowData">
            <input type="text" class="Form-input Form-input--long has-icon js-input" value="<%= current_user.client_application.key %>" readonly />
            <i data-title="Copy this" class="iconFont iconFont-Anchor Form-inputIcon Form-copyIcon js-copy-value"></i>
          </div>
          <div class="Form-rowInfo">
            <p class="Form-rowInfoText">Learn more about <%= link_to "using oauth in CartoDB", Cartodb.config[:developers_host] + "/cartodb-platform.html" %> in CartoDB.</p>
          </div>
        </div>

        <div class="Form-row">
          <div class="Form-rowLabel">
            <label class="Form-label">Consumer secret</label>
          </div>
          <div class="Form-rowData">
            <input type="text" class="Form-input Form-input--long has-icon js-input" value="<%= current_user.client_application.secret %>" readonly />
            <i data-title="Copy this" class="iconFont iconFont-Anchor Form-inputIcon Form-copyIcon js-copy-value"></i>
          </div>
        </div>

        <span class="Form-separator"></span>

        <div class="Form-row">
          <div class="Form-rowLabel">
            <label class="Form-label">Request token URL</label>
          </div>
          <div class="Form-rowData">
            <input type="text" class="Form-input Form-input--long has-icon js-input" value="<%= request_token_url(user_domain: params[:user_domain]) %>" readonly />
            <i data-title="Copy this" class="iconFont iconFont-Anchor Form-inputIcon Form-copyIcon js-copy-value"></i>
          </div>
        </div>

        <div class="Form-row">
          <div class="Form-rowLabel">
            <label class="Form-label">Access token URL</label>
          </div>
          <div class="Form-rowData">
            <input type="text" class="Form-input Form-input--long has-icon js-input" value="<%= access_token_url(user_domain: params[:user_domain]) %>" readonly />
            <i data-title="Copy this" class="iconFont iconFont-Anchor Form-inputIcon Form-copyIcon js-copy-value"></i>
          </div>
        </div>

        <div class="Form-footer">
          <p class="Form-footerText">
            <i class="iconFont iconFont-Info Form-footerIcon"></i>
            Learn more about <%= link_to "using your simple app key", Cartodb.config[:developers_host] + "/documentation/apis-overview.html" %> in CartoDB
          </p>
          <%= button_tag(type: 'submit', class: 'Button Button--main js-submit', value: 'oauth') do %>
            <% content_tag(:span, 'Request new oauth keys') %>
          <% end %>
        </div>

      <% end %>
    </div>
  </div>

</div>

<% if !Cartodb.config[:cartodb_com_hosted].present? %>
  <div class="SupportBanner" id="support-banner"></div>
<% end %>

<%= render 'admin/shared/new_footer' %>