config/routes.rb
# encoding: utf-8

# NOTES:
# (/u/:user_domain)                -> This allows support of org-urls (support != enforcement)
# defaults: { dont_rewrite: true } -> Use this to force an individual action to not get rewritten to org-url
# Can be also done at controller source files by using -> skip_before_filter :ensure_org_url_if_org_user

CartoDB::Application.routes.draw do
  # Double use: for user public dashboard AND org dashboard
  root :to => 'admin/pages#index'

  get   '(/u/:user_domain)/login'           => 'sessions#new',     as: :login
  get   '(/u/:user_domain)/logout'          => 'sessions#destroy', as: :logout
  match '(/u/:user_domain)/sessions/create' => 'sessions#create',  as: :create_session

  match '/limits' => 'home#limits', as: :limits
  match '/status' => 'home#app_status'

  # OAuth
  match '(/u/:user_domain)/oauth/authorize'      => 'oauth#authorize',     as: :authorize
  match '(/u/:user_domain)/oauth/request_token'  => 'oauth#request_token', as: :request_token
  match '(/u/:user_domain)/oauth/access_token'   => 'oauth#access_token',  as: :access_token
  get   '(/u/:user_domain)/oauth/identity'       => 'sessions#show',       as: :oauth_show_sessions

  get '/google_plus' => 'google_plus#google_plus'
  post '/google/signup' => 'google_plus#google_signup'

  # Internally, some of this methods will forcibly rewrite to the org-url if user belongs to an organization
  scope :module => :admin do

    # Organization dashboard page
    get    '(/u/:user_domain)/organization'                 => 'organizations#show',            as: :organization
    get    '(/u/:user_domain)/organization/settings'        => 'organizations#settings',        as: :organization_settings
    put    '(/u/:user_domain)/organization/settings'        => 'organizations#settings_update', as: :organization_settings_update
    # Organization users management
    get    '(/u/:user_domain)/organization/users/:id/edit'  => 'organization_users#edit',    as: :edit_organization_user,   constraints: { id: /[0-z\.\-]+/ }
    put    '(/u/:user_domain)/organization/users/:id'       => 'organization_users#update',  as: :update_organization_user, constraints: { id: /[0-z\.\-]+/ }
    post   '(/u/:user_domain)/organization/users'           => 'organization_users#create',  as: :create_organization_user
    delete '(/u/:user_domain)/organization/users/:id'       => 'organization_users#destroy', as: :delete_organization_user, constraints: { id: /[0-z\.\-]+/ }
    get    '(/u/:user_domain)/organization/users/new'       => 'organization_users#new',     as: :new_organization_user

    # User profile and account pages
    get    '(/u/:user_domain)/profile' => 'users#profile',        as: :profile_user
    put    '(/u/:user_domain)/profile' => 'users#profile_update', as: :profile_update_user
    get    '(/u/:user_domain)/account' => 'users#account',        as: :account_user
    delete '(/u/:user_domain)/account' => 'users#delete',        as: :account_user
    put    '(/u/:user_domain)/account' => 'users#account_update', as: :account_update_user
    delete '(/u/:user_domain)/account/:id' => 'users#delete', as: :delete_user

    # search
    get '(/u/:user_domain)/dashboard/search/:q'               => 'visualizations#index', as: :search
    get '(/u/:user_domain)/dashboard/search/:q/:page'         => 'visualizations#index', as: :search_page
    get '(/u/:user_domain)/dashboard/shared/search/:q'        => 'visualizations#index', as: :search_shared
    get '(/u/:user_domain)/dashboard/shared/search/:q/:page'  => 'visualizations#index', as: :search_shared_page

    # Tables
    get '(/u/:user_domain)/dashboard/tables'                            => 'visualizations#index', as: :tables_index
    get '(/u/:user_domain)/dashboard/tables/:page'                      => 'visualizations#index', as: :tables_page
    get '(/u/:user_domain)/dashboard/tables/tag/:tag'                   => 'visualizations#index', as: :tables_tag
    get '(/u/:user_domain)/dashboard/tables/tag/:tag/:page'             => 'visualizations#index', as: :tables_tag_page
    get '(/u/:user_domain)/dashboard/tables/shared'                     => 'visualizations#index', as: :tables_shared
    get '(/u/:user_domain)/dashboard/tables/shared/:page'               => 'visualizations#index', as: :tables_shared_page
    get '(/u/:user_domain)/dashboard/tables/shared/tag/:tag'            => 'visualizations#index', as: :tables_shared_tag
    get '(/u/:user_domain)/dashboard/tables/shared/tag/:tag/:page'      => 'visualizations#index', as: :tables_shared_tag_page
    get '(/u/:user_domain)/dashboard/tables/mine'                       => 'visualizations#index', as: :tables_mine
    get '(/u/:user_domain)/dashboard/tables/mine/:page'                 => 'visualizations#index', as: :tables_mine_page
    get '(/u/:user_domain)/dashboard/tables/mine/tag/:tag'              => 'visualizations#index', as: :tables_mine_tag
    get '(/u/:user_domain)/dashboard/tables/mine/tag/:tag/:page'        => 'visualizations#index', as: :tables_mine_tag_page
    get '(/u/:user_domain)/dashboard/tables/mine/locked'                => 'visualizations#index', as: :tables_mine_locked
    get '(/u/:user_domain)/dashboard/tables/mine/locked/:page'          => 'visualizations#index', as: :tables_mine_locked_page
    get '(/u/:user_domain)/dashboard/tables/mine/locked/tag/:tag'       => 'visualizations#index', as: :tables_mine_locked_tag
    get '(/u/:user_domain)/dashboard/tables/mine/locked/tag/:tag/:page' => 'visualizations#index', as: :tables_mine_locked_tag_page
    get '(/u/:user_domain)/dashboard/tables/locked'                     => 'visualizations#index', as: :tables_locked
    get '(/u/:user_domain)/dashboard/tables/locked/:page'               => 'visualizations#index', as: :tables_locked_page
    get '(/u/:user_domain)/dashboard/tables/locked/tag/:tag'            => 'visualizations#index', as: :tables_locked_tag
    get '(/u/:user_domain)/dashboard/tables/locked/tag/:tag/:page'      => 'visualizations#index', as: :tables_locked_tag_page

    # Datasets for new dashboard
    get '(/u/:user_domain)/dashboard/datasets'                              => 'visualizations#index', as: :datasets_index
    get '(/u/:user_domain)/dashboard/datasets/:page'                        => 'visualizations#index', as: :datasets_page
    get '(/u/:user_domain)/dashboard/datasets/tag/:tag'                     => 'visualizations#index', as: :datasets_tag
    get '(/u/:user_domain)/dashboard/datasets/tag/:tag/:page'               => 'visualizations#index', as: :datasets_tag_page
    get '(/u/:user_domain)/dashboard/datasets/shared'                       => 'visualizations#index', as: :datasets_shared
    get '(/u/:user_domain)/dashboard/datasets/shared/:page'                 => 'visualizations#index', as: :datasets_shared_page
    get '(/u/:user_domain)/dashboard/datasets/shared/tag/:tag'              => 'visualizations#index', as: :datasets_shared_tag
    get '(/u/:user_domain)/dashboard/datasets/shared/tag/:tag/:page'        => 'visualizations#index', as: :datasets_shared_tag_page
    get '(/u/:user_domain)/dashboard/datasets/shared/locked'                => 'visualizations#index', as: :datasets_shared_locked
    get '(/u/:user_domain)/dashboard/datasets/shared/locked/:page'          => 'visualizations#index', as: :datasets_shared_locked_page
    get '(/u/:user_domain)/dashboard/datasets/shared/locked/tag/:tag'       => 'visualizations#index', as: :datasets_shared_locked_tag
    get '(/u/:user_domain)/dashboard/datasets/shared/locked/tag/:tag/:page' => 'visualizations#index', as: :datasets_shared_locked_tag_page
    get '(/u/:user_domain)/dashboard/datasets/liked'                        => 'visualizations#index', as: :datasets_liked
    get '(/u/:user_domain)/dashboard/datasets/liked/:page'                  => 'visualizations#index', as: :datasets_liked_page
    get '(/u/:user_domain)/dashboard/datasets/liked/tag/:tag'               => 'visualizations#index', as: :datasets_liked_tag
    get '(/u/:user_domain)/dashboard/datasets/liked/tag/:tag/:page'         => 'visualizations#index', as: :datasets_liked_tag_page
    get '(/u/:user_domain)/dashboard/datasets/liked/locked'                 => 'visualizations#index', as: :datasets_liked_locked
    get '(/u/:user_domain)/dashboard/datasets/liked/locked/:page'           => 'visualizations#index', as: :datasets_liked_locked_page
    get '(/u/:user_domain)/dashboard/datasets/liked/locked/tag/:tag'        => 'visualizations#index', as: :datasets_liked_locked_tag
    get '(/u/:user_domain)/dashboard/datasets/liked/locked/tag/:tag/:page'  => 'visualizations#index', as: :datasets_liked_locked_tag_page
    get '(/u/:user_domain)/dashboard/datasets/locked'                       => 'visualizations#index', as: :datasets_locked
    get '(/u/:user_domain)/dashboard/datasets/locked/:page'                 => 'visualizations#index', as: :datasets_locked_page
    get '(/u/:user_domain)/dashboard/datasets/locked/tag/:tag'              => 'visualizations#index', as: :datasets_locked_tag
    get '(/u/:user_domain)/dashboard/datasets/locked/tag/:tag/:page'        => 'visualizations#index', as: :datasets_locked_tag_page
    get '(/u/:user_domain)/dashboard/datasets/library'                      => 'visualizations#index', as: :datasets_library
    get '(/u/:user_domain)/dashboard/datasets/library/:page'                => 'visualizations#index', as: :datasets_library_page
    get '(/u/:user_domain)/dashboard/datasets/library/tag/:tag'             => 'visualizations#index', as: :datasets_library_tag
    get '(/u/:user_domain)/dashboard/datasets/library/tag/:tag/:page'       => 'visualizations#index', as: :datasets_library_tag_page

    # Tables search
    get '(/u/:user_domain)/dashboard/tables/search/:q'                    => 'visualizations#index', as: :tables_search
    get '(/u/:user_domain)/dashboard/tables/search/:q/:page'              => 'visualizations#index', as: :tables_search_page

app/models/organization/organization_decorator.rb
module CartoDB
  module OrganizationDecorator
    def data(options = {})
      {
        created_at:        self.created_at,
        description:       self.description,
        discus_shortname:  self.discus_shortname,
        display_name:      self.display_name,
        id:                self.id,
        name:              self.name,
        owner: {
          id:         self.owner ? self.owner.id : nil,
          username:   self.owner ? self.owner.username : nil,
          avatar_url: self.owner ? self.owner.avatar_url : nil
        },
        quota_in_bytes:  self.quota_in_bytes,
        api_calls:       self.get_api_calls(from: self.owner.present? ? self.owner.last_billing_cycle : nil, to: Date.today),
        api_calls_quota: self.map_view_quota,
        geocoding: {
          quota:       self.geocoding_quota,
          monthly_use: self.get_geocoding_calls
        },
        twitter: {
          enabled:     self.twitter_datasource_enabled,
          quota:       self.twitter_datasource_quota,
          block_price: self.twitter_datasource_block_price,
          block_size:  self.twitter_datasource_block_size,
          monthly_use: self.get_twitter_imports_count
        },
        seats:             self.seats,
        twitter_username:  self.twitter_username,
        updated_at:        self.updated_at,
        users:             self.users.map { |u|
          {
            id:          u.id,
            username:    u.username,
            avatar_url:  u.avatar_url
          }
        },
        website:           self.website,
        avatar_url:        self.avatar_url,
        new_dashboard_enabled: self.new_dashboard_enabled
      }
    end
  end
end

app/controllers/admin/organizations_controller.rb
# coding: utf-8
class Admin::OrganizationsController < ApplicationController
  ssl_required :oauth, :api_key, :regenerate_api_key
  before_filter :login_required, :load_organization_and_members

  def show
    new_dashboard = current_user.has_feature_flag?('new_dashboard')
    view =  new_dashboard ? 'new_show' : 'show'
    layout = new_dashboard ? 'new_application' : 'application'

    respond_to do |format|
      format.html { render view, layout: layout }
    end
  end

  def settings
    new_dashboard = current_user.has_feature_flag?('new_dashboard')
    view =  new_dashboard ? 'new_settings' : 'settings'
    layout = new_dashboard ? 'new_application' : 'application'

    respond_to do |format|
      format.html { render view, layout: layout }
    end
  end

  def settings_update
    new_dashboard = current_user.has_feature_flag?('new_dashboard')
    view =  new_dashboard ? 'new_settings' : 'settings'
    layout = new_dashboard ? 'new_application' : 'application'

    attributes = params[:organization]

    if attributes.include?(:avatar_url)
      asset = Asset.new
      asset.raise_on_save_failure = true
      asset.user_id = current_user.id
      asset.asset_file = attributes[:avatar_url]
      asset.kind = Asset::KIND_ORG_AVATAR
      if asset.save
        @organization.avatar_url = asset.public_url
      end
    end

    @organization.website = attributes[:website]
    @organization.description = attributes[:description]
    @organization.display_name = attributes[:display_name]
    @organization.discus_shortname = attributes[:discus_shortname]
    @organization.twitter_username = attributes[:twitter_username]

    @organization.update_in_central
    @organization.save(raise_on_failure: true)

    redirect_to organization_settings_path(user_domain: params[:user_domain]), flash: { success: "Updated successfully" }
  rescue CartoDB::CentralCommunicationFailure => e
    @organization.reload
    flash.now[:error] = "There was a problem while updating your organization. Please, try again and contact us if the problem persists. #{e.user_message}"
    render action: view, layout: layout
  rescue Sequel::ValidationFailed => e
    flash.now[:error] = e.message
    render action: view, layout: layout
  end

  private

  def load_organization_and_members
    @organization = current_user.organization
    @users = current_user.organization.users
    raise RecordNotFound unless @organization.present? && current_user.organization_owner?
  end

end

app/controllers/api/json/organizations_controller.rb
# encoding: utf-8

class Api::Json::OrganizationsController < Api::ApplicationController
  include CartoDB

  if Rails.env.production? || Rails.env.staging?
    ssl_required :show, :users
  end

  # Fetch info from the current user orgranization
  def show
    render json: {}.to_json if current_user.organization.nil?

    render json: current_user.organization.to_poro
  end

  # Return user list of current user organization
  def users
    render json: {}.to_json if current_user.organization.nil?
    
    render json: current_user.organization.to_poro[:users]
  end

end

app/controllers/superadmin/organizations_controller.rb
class Superadmin::OrganizationsController < Superadmin::SuperadminController
  respond_to :json

  ssl_required :show, :create, :update, :destroy, :index if Rails.env.production? || Rails.env.staging?
  before_filter :get_organization, only: [:update, :destroy, :show]

  layout 'application'

  def show
    respond_with(@organization.data(:extended => true))
  end

  def index
    @organizations = (params[:overquota].present? ? Organization.overquota(0.20) : Organization.all)

    respond_with(:superadmin, @organizations.map(&:data))
  end

  def create
    @organization = Organization.new
    @organization.set_fields_from_central(params[:organization], :create)
    if @organization.save && params[:organization][:owner_id].present? && @organization.owner.nil?
      # TODO: move this into a callback or a model method
      uo = CartoDB::UserOrganization.new(@organization.id, params[:organization][:owner_id])
      uo.promote_user_to_admin
    end
    respond_with(:superadmin, @organization)
  end

  def update
    @organization.set_fields_from_central(params[:organization], :update)
    @organization.save
    respond_with(:superadmin, @organization)
  end

  def destroy
    @organization.destroy
    respond_with(:superadmin, @organization)
  end

  private

  def get_organization
    @organization = Organization[params[:id]]
    raise RecordNotFound unless @organization
  end # get_organization

end

app/views/admin/organizations/_settings_account.html.erb
<% if current_user.organization_owner? %>
  <nav class="account-settings">
    <div class="inner">
      <a href="<%= organization_url(user_domain: params[:user_domain]) %>"
         class="<%= 'selected' if ['admin/organizations', 'admin/users'].include?(params[:controller]) && !['settings'].include?(params[:action]) %>">
        <span class="icon organization"></span>
        <span class="info">
          <h2>Manage your seats</h2>
          <p><%= current_user.organization.users.count %> of <%= current_user.organization.seats %> in use</p>
        </span>
      </a>
      <a href="<%= organization_settings_url(user_domain: params[:user_domain]) %>"
         class="<%= 'selected' if ['settings'].include?(params[:action]) %>">
        <span class="icon stats"></span>
        <span class="info">
          <h2>Public dashboard</h2>
          <p>Configuration, logo,...</p>
        </span>
      </a>
      <% unless cartodb_com_hosted? %>
        <a href="<%= current_user.account_url(request.protocol) %>">
          <span class="icon settings"></span>
          <span class="info">
            <h2>Account settings</h2>
            <p>Invoicing, access,...</p>
          </span>
        </a>
      <% end %>
    </div>
  </nav>
<% end %>

app/views/admin/organizations/new_settings.html.erb
<% content_for(:page_title) do %>
  <%= current_user.organization.name %> settings |
<% end %>
<%= content_for(:js) do %>
  <script type="text/javascript">
    var username = "<%= current_user.username %>";
    var config = <%=raw frontend_config.html_safe %>;
    var user_data = <%= raw current_user.data.to_json.html_safe %>;
  </script>
  <%= javascript_include_tag 'cdb.js', 'models.js', 'new_organization_templates.js', 'new_organization_deps.js', 'new_organization.js' -%>
<% end %>

<%= render :partial => 'shared/new_flash_message' %>

<div>
  <%= render :partial => 'admin/shared/new_org_subheader' %>

  <div class="OrganizationContent">
    <div class="u-inner">
      <%= form_for @organization, url: organization_settings_update_path(user_domain: params[:user_domain]), multipart: true do |f| %>
        <%= csrf_meta_tags %>

        <div class="Form-title">
          <p class="Form-titleText">Edit your company settings</p>
        </div>

        <div class="Form-row">
          <div class="Form-rowLabel">
            <label class="Form-label">Public name</label>
          </div>
          <div class="Form-rowData">
            <%= f.text_field :name, :class => "Form-input Form-input--long" %>
          </div>
          <div class="Form-rowInfo">
            <p class="Form-rowInfoText">Check your <a href="<%= CartoDB.base_url(@organization.name) %>">public page</a></p>
          </div>
        </div>

        <div class="Form-row">
          <div class="Form-rowLabel">
            <label class="Form-label">Website</label>
          </div>
          <div class="Form-rowData">
            <%= f.text_field :website, :class => "Form-input Form-input--long" %>
          </div>
          <div class="Form-rowInfo">
            <p class="Form-rowInfoText"></p>
          </div>
        </div>

        <div class="Form-row">
          <div class="Form-rowLabel">
            <label class="Form-label">Description</label>
          </div>
          <div class="Form-rowData">
            <%= f.text_area :description, :class => "Form-textarea Form-input Form-input--long" %>
          </div>
          <div class="Form-rowInfo">
            <p class="Form-rowInfoText"></p>
          </div>
        </div>

        <div class="Form-row">
          <div class="Form-rowLabel">
            <label class="Form-label">Logo</label>
          </div>
          <div class="Form-rowData Form-avatar">
            <img src="<%= @organization.avatar_url %>" title="" alt="" class="Form-avatarPreview" />
            <%= f.file_field :avatar_url, :class => "js-fileAvatar", :value => "Change avatar" %>
          </div>
          <div class="Form-rowInfo">
            <p class="Form-rowInfoText">Recommended images should be 128x128 of size</p>
          </div>
        </div>

        <div class="Form-row">
          <div class="Form-rowLabel">
            <label class="Form-label">Twitter username</label>
          </div>
          <div class="Form-rowData">
            <%= f.text_field :twitter_username, :class => "Form-input Form-input--long" %>
          </div>
          <div class="Form-rowInfo">
            <p class="Form-rowInfoText"></p>
          </div>
        </div>

        <div class="Form-row">
          <div class="Form-rowLabel">
            <label class="Form-label">Disqus shortname</label>
          </div>
          <div class="Form-rowData">
            <%= f.text_field :discus_shortname, :class => "Form-input Form-input--long" %>
          </div>
          <div class="Form-rowInfo">
            <p class="Form-rowInfoText">Moderate the comments in your maps</p>
          </div>
        </div>

        <div class="Form-footer">
          <p class="Form-footerText"></p>
          <%= button_tag(type: 'submit', class: 'Button Button--main') do %>
            <% content_tag(:span, 'Save changes') %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

</div>

<% if !Cartodb.config[:cartodb_com_hosted].present? %>
  <div class="SupportBanner" id="support-banner"></div>
<% end %>

<%= render 'admin/shared/new_footer' %>

app/views/admin/organizations/new_show.html.erb
<% content_for(:page_title) do %>
  <%= current_user.organization.name %> |
<% end %>
<%= content_for(:js) do %>
  <script type="text/javascript">
    var username = "<%= current_user.username %>"
    var type = "oauth"
    var config = <%=raw frontend_config.html_safe %>
    var organization_quota = {
      seats: <%= current_user.organization.seats %>,
      quota_in_bytes: <%= current_user.organization.quota_in_bytes %>
    };
    var user_data = <%= raw current_user.data.to_json.html_safe %>;
  </script>
  <%= javascript_include_tag 'cdb.js', 'models.js', 'new_organization_templates.js', 'new_organization_deps.js', 'new_organization.js' -%>
<% end %>
<%= content_for(:css) do %>
  <%= stylesheet_link_tag  'new_organization.css',  :media => 'all' %>
<% end %>

<%= render :partial => 'shared/new_flash_message' %>

<div>
  <%= render :partial => 'admin/shared/new_org_subheader' %>

  <div class="OrganizationContent">
    <div class="u-inner">
      <div class="Form">

        <% totalPer = 0 %>

        <ul class="OrganizationList <% 'OrganizationList--centered' if @users.count === 4 %>">
          <% @users.each do |u| %>
            <li class="OrganizationList-user">
              <a class="OrganizationList-userLink" href="<%= edit_organization_user_path(user_domain: params[:user_domain], id: u.username) %>" data-title="<%= number_to_human_size(u.db_size_in_bytes) %> of <%= number_to_human_size(u.quota_in_bytes) %> used">
                <div class="OrganizationList-userAvatar UserAvatar">
                  <img src="<%= u.avatar_url %>" alt="<%= u.username %>" src="<%= u.username %>" class="UserAvatar-img UserAvatar-img--medium" />
                </div>
                <div class="OrganizationList-userInfo">
                  <div class="OrganizationList-userInfoName">
                    <h3 class="OrganizationList-userInfoTitle u-ellipsLongText"><%= u.username %></h3>
                    <% if u.organization_owner? %>
                      <span class="OrganizationList-userInfoLabel">OWNER</span>
                    <% end %>
                  </div>
                  <div class="OrganizationList-userStats">
                    <% userPer = ((u.quota_in_bytes * 100) / current_user.organization.quota_in_bytes ) %>
                    <% usedPer = ((u.db_size_in_bytes * 100) / current_user.organization.quota_in_bytes ) %>
                    <div class="progress-bar">
                      <span class="bar-2" style="left:<%= totalPer %>%; width:<%= userPer %>%"></span>
                      <span class="bar-3" style="left:<%= totalPer %>%; width:<%= usedPer %>%"></span>
                    </div>
                    <% totalPer = totalPer + userPer %>
                  </div>
                </div>
              </a>
            </li>
          <% end %>
          <% if current_user.organization.seats > @users.count %>
            <li class="OrganizationList-user OrganizationList-user--empty">
              <a class="OrganizationList-userLink" href="<%= new_organization_user_path(user_domain: params[:user_domain]) %>">
                <div class="OrganizationList-userAvatar OrganizationList-userAvatar--default">
                  <i class="iconFont iconFont-DefaultUser"></i>
                </div>
                <div class="OrganizationList-userInfo">
                  <div class="OrganizationList-userInfoName">
                    <h3 class="OrganizationList-userInfoTitle OrganizationList-userInfoTitle--default">Empty seat</h3>
                  </div>
                  <div class="OrganizationList-userInfoDes">Create new user</div>
                </div>
              </a>
            </li>
          <% end %>
        </ul>

        <div class="Form-footer">
          <% if current_user.organization.seats > @users.count %>
            <% if (current_user.organization.seats - @users.count) < 5 %>
              <p class="Form-footerText">
                <i class="iconFont iconFont-Info Form-footerIcon"></i>
                You are near your seats limit. Consider to <a href="<%= current_user.upgrade_url(request.protocol) %>">upgrade your account</a>.
              </p>
            <% else %>
              <em></em>
            <% end %>
            <a href="<%= new_organization_user_path(user_domain: params[:user_domain]) %>" class="Button Button--main"><span>Create new user</span></a>
          <% elsif !Cartodb.config[:cartodb_com_hosted].present? %>
            <p class="Form-footerText">
              <i class="iconFont iconFont-Info Form-footerIcon"></i>
              <a href="mailto:sales@cartodb.com">Contact us</a> if you have any question.
            </p>
            <a href="<%= current_user.upgrade_url(request.protocol) %>" class="Button Button--positive"><span>Upgrade account</span></a>
          <% end %>
        </div>
      </div>
    </div>
  </div>

</div>

<% if !Cartodb.config[:cartodb_com_hosted].present? %>
  <div class="SupportBanner" id="support-banner"></div>
<% end %>

<%= render 'admin/shared/new_footer' %>

app/views/admin/organizations/show.html.erb
<% content_for(:page_title) do %>
  Your organization |
<% end %>
<%= content_for(:js) do %>
  <%= javascript_include_tag 'cdb.js', 'application.js', 'models.js', 'organization.js', 'templates.js' %>
  <script type="text/javascript">
    var username = "<%= current_user.username %>"
      , type = "oauth"
      , config = <%=raw frontend_config.html_safe %>
      , organization_quota = {
          seats: <%= current_user.organization.seats %>,
          quota_in_bytes: <%= current_user.organization.quota_in_bytes %>
        }
      , organization_users = <%= raw @users.map { |u| {
          id: u.id,
          username: u.username,
          avatar_url: u.avatar_url,
          quota_in_bytes: u.quota_in_bytes,
          remaining_quota: u.remaining_quota,
          organization_owner: u.organization_owner?
        }}.to_json -%>
      , user_data = <%= raw current_user.data.to_json.html_safe %>;
  </script>
<% end %>
<%= content_for(:css) do %>
  <%= stylesheet_link_tag 'common.css', 'organization.css', :media => 'all' %>
<% end %>

<%= content_for(:account_settings) do %>
  <%= render partial: "settings_account" %>
<% end %>

<article>
  <div class="inner">
    <section class="block">
      <div class="head">
        <h2><%= current_user.organization.name.humanize %>'s users</h2>
      </div>
      <ul><%= render :partial => 'shared/flash_message' %></ul>
      <div class="list-head">
        <ul>
          <li><label>username</label></li>
          <li><label>quota</label></li>
        </ul>
      </div>
      <div class="content users_list">
        <ul>
          <% @users.each do |user| -%>
          <li>
            <div class="info">
              <%= link_to user.username, edit_organization_user_path(user_domain: params[:user_domain], id: user.username) %>
              <% if user.organization_owner? %>
                <span class="status owner">OWNER</span>
              <% end %>
            </div>
            <div class="storage">
              <div class="progress-bar"></div>
            </div>
          </li>
          <% end -%>
        </ul>
      </div>
      <div class="foot">
        <% if current_user.organization.seats > @users.count %>
          <%= link_to "Create new user", new_organization_user_path(user_domain: params[:user_domain]), :class => 'right button grey' %>
          <% unless cartodb_com_hosted? %>
            <%= link_to "Buy more seats", current_user.upgrade_url(request.protocol), :class => 'margin10 underline left' %>
          <% end %>
        <% else %>
          <% unless cartodb_com_hosted? %>
            <%= link_to "Upgrade your quota", current_user.upgrade_url(request.protocol), :class => "button green right" %>
          <% end %>
        <% end %>
      </div>
    </section>
  </div>
</article>