config/routes.rb
# encoding: utf-8

# NOTES:
# (/u/:user_domain)                -> This allows support of org-urls (support != enforcement)
# defaults: { dont_rewrite: true } -> Use this to force an individual action to not get rewritten to org-url
# Can be also done at controller source files by using -> skip_before_filter :ensure_org_url_if_org_user

CartoDB::Application.routes.draw do
  # Double use: for user public dashboard AND org dashboard
  root :to => 'admin/pages#index'

  get   '(/u/:user_domain)/login'           => 'sessions#new',     as: :login
  get   '(/u/:user_domain)/logout'          => 'sessions#destroy', as: :logout
  match '(/u/:user_domain)/sessions/create' => 'sessions#create',  as: :create_session

  match '/limits' => 'home#limits', as: :limits
  match '/status' => 'home#app_status'

  # OAuth
  match '(/u/:user_domain)/oauth/authorize'      => 'oauth#authorize',     as: :authorize
  match '(/u/:user_domain)/oauth/request_token'  => 'oauth#request_token', as: :request_token
  match '(/u/:user_domain)/oauth/access_token'   => 'oauth#access_token',  as: :access_token
  get   '(/u/:user_domain)/oauth/identity'       => 'sessions#show',       as: :oauth_show_sessions

  get '/google_plus' => 'google_plus#google_plus'
  post '/google/signup' => 'google_plus#google_signup'

  # Internally, some of this methods will forcibly rewrite to the org-url if user belongs to an organization
  scope :module => :admin do

    # Organization dashboard page
    get    '(/u/:user_domain)/organization'                 => 'organizations#show',            as: :organization
    get    '(/u/:user_domain)/organization/settings'        => 'organizations#settings',        as: :organization_settings
    put    '(/u/:user_domain)/organization/settings'        => 'organizations#settings_update', as: :organization_settings_update
    # Organization users management
    get    '(/u/:user_domain)/organization/users/:id/edit'  => 'organization_users#edit',    as: :edit_organization_user,   constraints: { id: /[0-z\.\-]+/ }
    put    '(/u/:user_domain)/organization/users/:id'       => 'organization_users#update',  as: :update_organization_user, constraints: { id: /[0-z\.\-]+/ }
    post   '(/u/:user_domain)/organization/users'           => 'organization_users#create',  as: :create_organization_user
    delete '(/u/:user_domain)/organization/users/:id'       => 'organization_users#destroy', as: :delete_organization_user, constraints: { id: /[0-z\.\-]+/ }
    get    '(/u/:user_domain)/organization/users/new'       => 'organization_users#new',     as: :new_organization_user

    # User profile and account pages
    get    '(/u/:user_domain)/profile' => 'users#profile',        as: :profile_user
    put    '(/u/:user_domain)/profile' => 'users#profile_update', as: :profile_update_user
    get    '(/u/:user_domain)/account' => 'users#account',        as: :account_user
    delete '(/u/:user_domain)/account' => 'users#delete',        as: :account_user
    put    '(/u/:user_domain)/account' => 'users#account_update', as: :account_update_user
    delete '(/u/:user_domain)/account/:id' => 'users#delete', as: :delete_user

    # search
    get '(/u/:user_domain)/dashboard/search/:q'               => 'visualizations#index', as: :search
    get '(/u/:user_domain)/dashboard/search/:q/:page'         => 'visualizations#index', as: :search_page
    get '(/u/:user_domain)/dashboard/shared/search/:q'        => 'visualizations#index', as: :search_shared
    get '(/u/:user_domain)/dashboard/shared/search/:q/:page'  => 'visualizations#index', as: :search_shared_page

    # Tables
    get '(/u/:user_domain)/dashboard/tables'                            => 'visualizations#index', as: :tables_index
    get '(/u/:user_domain)/dashboard/tables/:page'                      => 'visualizations#index', as: :tables_page
    get '(/u/:user_domain)/dashboard/tables/tag/:tag'                   => 'visualizations#index', as: :tables_tag
    get '(/u/:user_domain)/dashboard/tables/tag/:tag/:page'             => 'visualizations#index', as: :tables_tag_page
    get '(/u/:user_domain)/dashboard/tables/shared'                     => 'visualizations#index', as: :tables_shared
    get '(/u/:user_domain)/dashboard/tables/shared/:page'               => 'visualizations#index', as: :tables_shared_page
    get '(/u/:user_domain)/dashboard/tables/shared/tag/:tag'            => 'visualizations#index', as: :tables_shared_tag
    get '(/u/:user_domain)/dashboard/tables/shared/tag/:tag/:page'      => 'visualizations#index', as: :tables_shared_tag_page
    get '(/u/:user_domain)/dashboard/tables/mine'                       => 'visualizations#index', as: :tables_mine
    get '(/u/:user_domain)/dashboard/tables/mine/:page'                 => 'visualizations#index', as: :tables_mine_page
    get '(/u/:user_domain)/dashboard/tables/mine/tag/:tag'              => 'visualizations#index', as: :tables_mine_tag
    get '(/u/:user_domain)/dashboard/tables/mine/tag/:tag/:page'        => 'visualizations#index', as: :tables_mine_tag_page
    get '(/u/:user_domain)/dashboard/tables/mine/locked'                => 'visualizations#index', as: :tables_mine_locked
    get '(/u/:user_domain)/dashboard/tables/mine/locked/:page'          => 'visualizations#index', as: :tables_mine_locked_page
    get '(/u/:user_domain)/dashboard/tables/mine/locked/tag/:tag'       => 'visualizations#index', as: :tables_mine_locked_tag
    get '(/u/:user_domain)/dashboard/tables/mine/locked/tag/:tag/:page' => 'visualizations#index', as: :tables_mine_locked_tag_page
    get '(/u/:user_domain)/dashboard/tables/locked'                     => 'visualizations#index', as: :tables_locked
    get '(/u/:user_domain)/dashboard/tables/locked/:page'               => 'visualizations#index', as: :tables_locked_page
    get '(/u/:user_domain)/dashboard/tables/locked/tag/:tag'            => 'visualizations#index', as: :tables_locked_tag
    get '(/u/:user_domain)/dashboard/tables/locked/tag/:tag/:page'      => 'visualizations#index', as: :tables_locked_tag_page

    # Datasets for new dashboard
    get '(/u/:user_domain)/dashboard/datasets'                              => 'visualizations#index', as: :datasets_index
    get '(/u/:user_domain)/dashboard/datasets/:page'                        => 'visualizations#index', as: :datasets_page
    get '(/u/:user_domain)/dashboard/datasets/tag/:tag'                     => 'visualizations#index', as: :datasets_tag
    get '(/u/:user_domain)/dashboard/datasets/tag/:tag/:page'               => 'visualizations#index', as: :datasets_tag_page
    get '(/u/:user_domain)/dashboard/datasets/shared'                       => 'visualizations#index', as: :datasets_shared
    get '(/u/:user_domain)/dashboard/datasets/shared/:page'                 => 'visualizations#index', as: :datasets_shared_page
    get '(/u/:user_domain)/dashboard/datasets/shared/tag/:tag'              => 'visualizations#index', as: :datasets_shared_tag
    get '(/u/:user_domain)/dashboard/datasets/shared/tag/:tag/:page'        => 'visualizations#index', as: :datasets_shared_tag_page
    get '(/u/:user_domain)/dashboard/datasets/shared/locked'                => 'visualizations#index', as: :datasets_shared_locked
    get '(/u/:user_domain)/dashboard/datasets/shared/locked/:page'          => 'visualizations#index', as: :datasets_shared_locked_page
    get '(/u/:user_domain)/dashboard/datasets/shared/locked/tag/:tag'       => 'visualizations#index', as: :datasets_shared_locked_tag
    get '(/u/:user_domain)/dashboard/datasets/shared/locked/tag/:tag/:page' => 'visualizations#index', as: :datasets_shared_locked_tag_page
    get '(/u/:user_domain)/dashboard/datasets/liked'                        => 'visualizations#index', as: :datasets_liked
    get '(/u/:user_domain)/dashboard/datasets/liked/:page'                  => 'visualizations#index', as: :datasets_liked_page
    get '(/u/:user_domain)/dashboard/datasets/liked/tag/:tag'               => 'visualizations#index', as: :datasets_liked_tag
    get '(/u/:user_domain)/dashboard/datasets/liked/tag/:tag/:page'         => 'visualizations#index', as: :datasets_liked_tag_page
    get '(/u/:user_domain)/dashboard/datasets/liked/locked'                 => 'visualizations#index', as: :datasets_liked_locked
    get '(/u/:user_domain)/dashboard/datasets/liked/locked/:page'           => 'visualizations#index', as: :datasets_liked_locked_page
    get '(/u/:user_domain)/dashboard/datasets/liked/locked/tag/:tag'        => 'visualizations#index', as: :datasets_liked_locked_tag
    get '(/u/:user_domain)/dashboard/datasets/liked/locked/tag/:tag/:page'  => 'visualizations#index', as: :datasets_liked_locked_tag_page
    get '(/u/:user_domain)/dashboard/datasets/locked'                       => 'visualizations#index', as: :datasets_locked
    get '(/u/:user_domain)/dashboard/datasets/locked/:page'                 => 'visualizations#index', as: :datasets_locked_page
    get '(/u/:user_domain)/dashboard/datasets/locked/tag/:tag'              => 'visualizations#index', as: :datasets_locked_tag
    get '(/u/:user_domain)/dashboard/datasets/locked/tag/:tag/:page'        => 'visualizations#index', as: :datasets_locked_tag_page
    get '(/u/:user_domain)/dashboard/datasets/library'                      => 'visualizations#index', as: :datasets_library
    get '(/u/:user_domain)/dashboard/datasets/library/:page'                => 'visualizations#index', as: :datasets_library_page
    get '(/u/:user_domain)/dashboard/datasets/library/tag/:tag'             => 'visualizations#index', as: :datasets_library_tag
    get '(/u/:user_domain)/dashboard/datasets/library/tag/:tag/:page'       => 'visualizations#index', as: :datasets_library_tag_page

    # Tables search
    get '(/u/:user_domain)/dashboard/tables/search/:q'                    => 'visualizations#index', as: :tables_search
    get '(/u/:user_domain)/dashboard/tables/search/:q/:page'              => 'visualizations#index', as: :tables_search_page

app/controllers/admin/users_controller.rb
# coding: utf-8
require_relative '../../../lib/google_plus_api'
require_relative '../../../lib/google_plus_config'

class Admin::UsersController < ApplicationController
  ssl_required  :account, :profile, :account_update, :profile_update, :delete

  before_filter :login_required
  before_filter :setup_user
  before_filter :initialize_google_plus_config, only: [:profile, :account]

  def initialize_google_plus_config
    signup_action = Cartodb::Central.sync_data_with_cartodb_central? ? Cartodb::Central.new.google_signup_url : '/google/signup'
    @google_plus_config = ::GooglePlusConfig.instance(Cartodb.config, signup_action)
  end

  def profile
    unless @user.has_feature_flag?('new_dashboard')
      redirect_to @user.account_url(request.protocol) and return
    end

    respond_to do |format|
      format.html { render 'profile', layout: 'new_application' }
    end
  end

  def account
    unless @user.has_feature_flag?('new_dashboard')
      redirect_to @user.account_url(request.protocol) and return
    end

    respond_to do |format|
      format.html { render 'account', layout: 'new_application' }
    end
  end

  def account_update
    attributes = params[:user]
    if attributes[:new_password].present? || attributes[:confirm_password].present?
      @user.change_password(
        attributes[:old_password].presence,
        attributes[:new_password].presence,
        attributes[:confirm_password].presence
      )
    end

    if @user.can_change_email && attributes[:email].present?
      @user.set_fields(attributes, [:email])
    end
    
    @user.update_in_central
    @user.save(raise_on_failure: true)

    redirect_to account_user_path(user_domain: params[:user_domain]), flash: { success: "Updated successfully" }
  rescue CartoDB::CentralCommunicationFailure => e
    Rollbar.report_exception(e, params, @user)
    flash.now[:error] = "There was a problem while updating your data. Please, try again and contact us if the problem persists"
    render action: :account, layout: 'new_application'
  rescue Sequel::ValidationFailed => e
    flash.now[:error] = "Error updating your account details"
    render action: :account, layout: 'new_application'
  end

  def profile_update
    attributes = params[:user]

    if attributes[:avatar_url].present?
      asset = Asset.new
      asset.raise_on_save_failure = true
      asset.user_id = @user.id
      asset.asset_file = attributes[:avatar_url]
      asset.kind = Asset::KIND_ORG_AVATAR
      if asset.save
        @user.avatar_url = asset.public_url
      end
    end

    # This fields are optional
    @user.name = attributes.fetch(:name, nil)
    @user.website = attributes.fetch(:website, nil)
    @user.description = attributes.fetch(:description, nil)
    @user.twitter_username = attributes.fetch(:twitter_username, nil)
    @user.disqus_shortname = attributes.fetch(:disqus_shortname, nil)

    @user.set_fields(attributes, [:available_for_hire]) if attributes[:available_for_hire].present?

    @user.update_in_central
    @user.save(raise_on_failure: true)

    redirect_to profile_user_path(user_domain: params[:user_domain]), flash: { success: "Updated successfully" }
  rescue CartoDB::CentralCommunicationFailure => e
    Rollbar.report_exception(e, params, @user)
    flash.now[:error] = "There was a problem while updating your data. Please, try again and contact us if the problem persists"
    render action: :profile, layout: 'new_application'
  rescue Sequel::ValidationFailed => e
    flash.now[:error] = "Error updating your profile details"
    render action: :profile, layout: 'new_application'
  end

  def delete
    deletion_password_confirmation = params[:deletion_password_confirmation]
    if !@user.validate_old_password(deletion_password_confirmation)
      raise 'Password does not match'
    end

    @user.delete_in_central
    @user.destroy

    if Cartodb::Central.sync_data_with_cartodb_central?
      redirect_to "http://www.cartodb.com"
    else
      render(file: "public/404.html", layout: false, status: 404)
    end
  rescue CartoDB::CentralCommunicationFailure => e
    Rollbar.report_message('Central error deleting user at CartoDB', 'error', { user: @user.inspect, error: e.inspect })
    flash.now[:error] = "Error deleting user: #{e.user_message}"
    render 'account', layout: 'new_application'
  rescue => e
    Rollbar.report_message('Error deleting user at CartoDB', 'error', { user: @user.inspect, error: e.inspect })
    flash.now[:error] = "Error deleting user: #{e.message}"
    render action: :account, layout: 'new_application'
  end

  private

  def setup_user
    @user = current_user
  end

end

app/controllers/superadmin/users_controller.rb
class Superadmin::UsersController < Superadmin::SuperadminController
  respond_to :json

  ssl_required :show, :create, :update, :destroy, :index if Rails.env.production? || Rails.env.staging?
  before_filter :get_user, only: [:update, :destroy, :show, :dump, :data_imports, :data_import]

  layout 'application'

  def show
    respond_with(@user.data(:extended => true))
  end

  def index
    @users = (params[:overquota].present? ? User.overquota(0.20) : User.all)
    respond_with(:superadmin, @users.map(&:data))
  end

  def create
    @user = User.new

    @user.set_fields_from_central(params[:user], :create)
    @user.enabled = true

    if @user.save
      @user.reload
      @user.set_relationships_from_central(params[:user])
    end
    respond_with(:superadmin, @user)
  end

  def update
    @user.set_fields_from_central(params[:user], :update)
    @user.set_relationships_from_central(params[:user])

    @user.save
    respond_with(:superadmin, @user)
  end

  def destroy
    @user.destroy
    respond_with(:superadmin, @user)
  end

  def dump
    if Cartodb.config[:users_dumps].nil? || Cartodb.config[:users_dumps]["service"].nil? || Cartodb.config[:users_dumps]["service"]["port"].nil?
      raise "There is not a dump method configured"
    end
    json_data = {database: @user.database_name, username: @user.username}
    response = Typhoeus::Request.new(
      "#{@user.database_host}:#{Cartodb.config[:users_dumps]["service"]["port"]}/scripts/db_dump",
      method: :post,
      headers: { "Content-Type" => "application/json" },
      body: json_data.to_json
    ).run
    parsed_response = JSON.parse(response.body)
    if response.code == 200 && 
       parsed_response['retcode'] == 0 &&
       !parsed_response['return_values']['local_file'].nil? &&
       !parsed_response['return_values']['local_file'].empty? &&
       !parsed_response['return_values']['remote_file'].nil? &&
       !parsed_response['return_values']['remote_file'].empty?
      sa_response = {
        :dumper_response => parsed_response,
        :remote_file => parsed_response['remote_file'],
        :local_file => parsed_response['local_file'],
        :database_host => @user.database_host
      }
      render json: sa_response, status: 200
    else
      sa_response = {
        :dumper_response => parsed_response
      }
      render json: sa_response, status: 400   
    end
  end

  def data_imports
    respond_with(@user.data_imports_dataset.map { |entry|
      {
        id: entry.id,
        data_type: entry.data_type,
        date: entry.updated_at,
        status: entry.success.nil? ? false : entry.success
      }
    })
  end

  def data_import
    data_import = DataImport[params[:data_import_id]]
    respond_with({
                   data: data_import,
                   log: data_import.nil? ? nil : data_import.log.entries
                 })
  end

  private

  def get_user
    @user = User[params[:id]]
    raise RecordNotFound unless @user
  end # get_user

end # Superadmin::UsersController

app/views/admin/users/account.html.erb
<% content_for(:page_title) do %>
  Your account |
<% end %>
<%= content_for(:js) do %>
  <script type="text/javascript">
    var username = "<%= @user.username %>";
    var config = <%=raw frontend_config.html_safe %>;
    var authenticity_token = "<%= form_authenticity_token %>";
    var user_data = <%= raw @user.data.to_json.html_safe %>;
  </script>
  <%= javascript_include_tag 'cdb.js', 'models.js', 'account_templates.js', 'account_deps.js', 'account.js' -%>
<% end %>

<%= render :partial => 'shared/new_flash_message' %>

<div>
  <%= render :partial => 'admin/shared/new_pages_subheader' %>

  <div class="CredentialsContent">
    <div class="u-inner">
      <%= form_for @user, url: account_update_user_path(user_domain: params[:user_domain]), :class => "Form" do |f| %>
        <%= csrf_meta_tags %>

        <div class="Form-title">
          <p class="Form-titleText">Change your account preferences</p>
        </div>

        <div class="Form-row">
          <div class="Form-rowLabel">
            <label class="Form-label">Username</label>
          </div>
          <div class="Form-rowData">
            <%= f.text_field :username, readonly: true, :class => "Form-input Form-input--long is-disabled" %>
          </div>
          <div class="Form-rowInfo">
            <p class="Form-rowInfoText">Subdomain cannot be changed</p>
          </div>
        </div>

        <div class="Form-row">
          <div class="Form-rowLabel">
            <label class="Form-label">Email</label>
          </div>
          <div class="Form-rowData">
            <%= f.text_field :email, class: "Form-input Form-input--long #{ 'Form-input--error' if @user.errors[:email].present? } #{ 'is-disabled' unless @user.can_change_email }", readonly: !@user.can_change_email %>
          </div>
          <div class="Form-rowInfo">
            <% if @user.errors[:email].present? %>
              <p class="Form-rowInfoText Form-rowInfoText--error">Email not valid</p>
            <% elsif @user.google_sign_in %>
              <p class="Form-rowInfoText <%= 'Form-rowInfoText--multipleLines' unless @user.should_display_old_password? %>">Your account is linked to your Google account. <% unless @user.should_display_old_password? %> You can change the email if you set a password.</p> <% end %>
            <% end %>
          </div>
        </div>

        <% if @user.should_display_old_password? %>
          <div class="Form-row">
            <div class="Form-rowLabel">
              <label class="Form-label">Old password</label>
            </div>
            <div class="Form-rowData">
              <%= f.password_field :old_password, :class => "Form-input Form-input--long #{ 'Form-input--error' if @user.errors[:old_password].present? }" %>
            </div>
            <div class="Form-rowInfo">
              <% if (@user.errors[:old_password].present?) %>
                <p class="Form-rowInfoText Form-rowInfoText--error"><%= @user.errors[:old_password].first%></p>
              <% end %>
            </div>
          </div>
        <% end %>

        <div class="Form-row">
          <div class="Form-rowLabel">
            <label class="Form-label">New password</label>
          </div>
          <div class="Form-rowData">
            <%= f.password_field :new_password, :class => "Form-input Form-input--long #{ 'Form-input--error' if @user.errors[:new_password].present? }" %>
          </div>
          <div class="Form-rowInfo">
            <% if (@user.errors[:new_password].present?) %>
              <p class="Form-rowInfoText Form-rowInfoText--error"><%= @user.errors[:new_password].first%></p>
            <% else %>
              <p class="Form-rowInfoText">Password should be 6 characters at least</p>
            <% end %>
          </div>
        </div>

        <div class="Form-row">
          <div class="Form-rowLabel">
            <label class="Form-label">Confirm password</label>
          </div>
          <div class="Form-rowData">
            <%= f.password_field :confirm_password, :class => "Form-input Form-input--long" %>
          </div>
        </div>

        <div class="Form-footer">
          <% if !current_user.organization_owner? -%>
            <button class="Button Button--secondary js-deleteAccount">
              <span>Delete my account</span>
            </button>
          <% else %>
            <p class="Form-footerText">
              <i class="iconFont iconFont-Info Form-footerIcon"></i>
              You can't delete your account because you are admin of an organization
            </p>
          <% end %>
          <%= button_tag(type: 'submit', class: 'Button Button--main') do %>
            <% content_tag(:span, 'Save changes') %>
          <% end %>
        </div>

      <% end %>
    </div>
  </div>

</div>

<% if !Cartodb.config[:cartodb_com_hosted].present? %>
  <div class="SupportBanner" id="support-banner"></div>
<% end %>

<%= render 'admin/shared/new_footer' %>

app/views/admin/users/profile.html.erb
<% content_for(:page_title) do %>
  Your profile |
<% end %>
<%= content_for(:js) do %>
  <script type="text/javascript">
    var username = "<%= @user.username %>";
    var config = <%=raw frontend_config.html_safe %>;
    var user_data = <%= raw @user.data.to_json.html_safe %>;
  </script>
  <%= javascript_include_tag 'cdb.js', 'models.js', 'account_templates.js', 'account_deps.js', 'account.js' -%>
<% end %>


<%= render :partial => 'shared/new_flash_message' %>

<div>
  <%= render :partial => 'admin/shared/new_pages_subheader' %>

  <div class="CredentialsContent">
    <div class="u-inner">
      <%= form_for @user, url: profile_update_user_path(user_domain: params[:user_domain], id: @user.username) do |f| %>
        <%= csrf_meta_tags %>

        <div class="Form-title">
          <p class="Form-titleText">Edit your profile settings  </p>
        </div>

        <div class="Form-row">
          <div class="Form-rowLabel">
            <label class="Form-label">Name</label>
          </div>
          <div class="Form-rowData">
            <%= f.text_field :name, :class => "Form-input Form-input--long" %>
          </div>
          <div class="Form-rowInfo">
            <p class="Form-rowInfoText">Other users would reach you by your public name</p>
          </div>
        </div>

        <div class="Form-row">
          <div class="Form-rowLabel">
            <label class="Form-label">Website</label>
          </div>
          <div class="Form-rowData">
            <%= f.text_field :website, :class => "Form-input Form-input--long" %>
          </div>
          <div class="Form-rowInfo">
            <p class="Form-rowInfoText"></p>
          </div>
        </div>

        <div class="Form-row">
          <div class="Form-rowLabel">
            <label class="Form-label">Your description</label>
          </div>
          <div class="Form-rowData">
            <%= f.text_area :description, :class => "Form-textarea Form-input Form-input--long" %>
          </div>
          <div class="Form-rowInfo">
            <p class="Form-rowInfoText"></p>
          </div>
        </div>

        <div class="Form-row">
          <div class="Form-rowLabel">
            <label class="Form-label">Avatar</label>
          </div>
          <div class="Form-rowData Form-avatar">
            <img src="<%= @user.avatar_url %>" title="" alt="" class="Form-avatarPreview" />
            <%= f.file_field :avatar_url, :class => "js-fileAvatar", :value => "Change avatar" %>
          </div>
          <div class="Form-rowInfo">
            <p class="Form-rowInfoText">Recommended images should be 128x128 of size</p>
          </div>
        </div>

        <div class="Form-row">
          <div class="Form-rowLabel">
            <label class="Form-label">Twitter username</label>
          </div>
          <div class="Form-rowData">
            <%= f.text_field :twitter_username, :class => "Form-input Form-input--long" %>
          </div>
          <div class="Form-rowInfo">
            <p class="Form-rowInfoText"></p>
          </div>
        </div>

        <div class="Form-row">
          <div class="Form-rowLabel">
            <label class="Form-label">Disqus shortname</label>
          </div>
          <div class="Form-rowData">
            <%= f.text_field :disqus_shortname, :class => "Form-input Form-input--long" %>
          </div>
          <div class="Form-rowInfo">
            <p class="Form-rowInfoText">Moderate the comments in your maps</p>
          </div>
        </div>

        <div class="Form-row">
          <div class="Form-rowLabel">
            <label class="Form-label">Available for hire</label>
          </div>
          <div class="Form-rowData">
            <div class="Toggler">
              <%= f.check_box :available_for_hire, :id => "available_for_hire" %>
              <%= label_tag(:available_for_hire, '') %>
            </div>
          </div>
          <div class="Form-rowInfo">
            <p class="Form-rowInfoText">Show a banner in your public profile linked to your email</p>
          </div>
        </div>

        <div class="Form-footer">
          <p class="Form-footerText"></p>
          <%= button_tag(type: 'submit', class: 'Button Button--main') do %>
            <% content_tag(:span, 'Save changes') %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

</div>

<% if !Cartodb.config[:cartodb_com_hosted].present? %>
  <div class="SupportBanner" id="support-banner"></div>
<% end %>

<%= render 'admin/shared/new_footer' %>